### ISSUE TITLE
Enable Full Width Layout not maintained after setting

### ISSUE THREAD

**Issue by AlkalineCandy79** [bitwarden/server#1886] opened 2022-02-27 18:41 UTC
### Steps To Reproduce

1. Go to settings.
2. Click on options
3. Enable Full Width Layout
4. Click Save
5. Close Chrome.
6. Open Chrome and log back in.

### Expected Result

Full width sticks.

### Actual Result

A checkmark remains in full width, but it is back to the original settings (not full width).

### Build Version

2.26.1

### Environment

Self-Hosted

### Environment Details

Docker.

**Comment by djsmith85** [comment] 2022-03-01 13:17
@AlkalineCandy79 Thank you for your report. Closing this as a duplicate of https://github.com/bitwarden/web/issues/1505

**Closed by djsmith85** 2022-03-01 13:17 UTC
Labels: bug
