### ISSUE TITLE
Organization user of type Admin is allowed to demote user of type Owner

### ISSUE THREAD

**Issue by milosvvv** [bitwarden/server#467] opened 2019-03-27 12:24 UTC
I understand that for a user of type admin it says "Admins can access and manage all items, collections and **users** in your organization." but they should not be allowed to remove Owner privileges from what is essentially the only superuser in the organization that can control everything and everyone. 

I'm also partial on allowing Admins to demote themselves, as now an Admin can turn themselves into a Manager or User. Admin should only be allowed to change Manager and Users, and Owner should be allowed to change everyone

**Comment by kspearrin** [comment] 2019-03-28 16:38
Fixed in next version.

> Luckily we made 2 owners otherwise I'd have to reinstall the whole thing.

This would have been prevented due to another check that verifies the org has at least 1 owner.

**Closed** 2019-03-28 16:37 UTC

**Comment by jeffgoh** [comment] 2020-03-24 14:26
I have a slight problem - I set my wife to own her own organization, and then demoted myself to admin. she accepted but I didn't know I needed to confirm, so now the organization has only one owner who isn't confirmed, so really no owners.
