### ISSUE TITLE
Push notifications are not working

### ISSUE THREAD

**Issue by btr3** [bitwarden/server#835] opened 2020-07-22 14:16 UTC
Android / iOS push notifications are not working. If I add an entry via Bitwarden web, desktop, or extension it will not be pushed to the mobile application. This is problematic when the autofill dialog opens on mobile because the entry will not be in the list on the app. In order to update the autofill options, you have to open Bitwarden to sync the vault and then the next time you use autofill it will be up to date for the time being.

**Comment by clayadams5226** [comment] 2020-07-23 04:47
This issue is currently being tracked on [](https://github.com/bitwarden/mobile/issues/980)

**Comment by cscharf** [comment] 2020-07-23 12:47
Closing as this is a duplicate of https://github.com/bitwarden/mobile/issues/980

**Closed by cscharf** 2020-07-23 12:47 UTC
