### ISSUE TITLE
Renew SSL Certificates Automatically

### ISSUE THREAD

**Issue by hc-danieltiziani** [bitwarden/server#627] opened 2019-12-27 09:15 UTC
Is there any way to renew the ssl certificates without using ./bitwarden.sh restart ?

Also, is there a way to schedule those restarts in a good way (say each month) to get the certificates updated automatically? I have the team installation in an ubuntu instance.

**Comment by kspearrin** [comment] 2019-12-27 15:28
Just use certbot:
https://certbot.eff.org/
https://hub.docker.com/r/certbot/certbot/

This is what the scripts use.


You can create a cron to restart bitwarden on whatever schedule you like.

**Comment by hc-danieltiziani** [comment] 2019-12-28 14:46
Hi @kspearrin , I know about certbot, but as I configured the default options to bitwarden to create/renew, I'd like to check the best practices regarding automating this, even if it means restarting the whole bitwarden server. But sure would be nice to have a way to avoid downtimes and just restart part of it.

Thanks anyway.

**Comment by kspearrin** [comment] 2019-12-29 18:43
I think you would at least still need to restart the nginx container for it to pick up the new cert files.

**Comment by kevdogg** [comment] 2020-02-04 19:58
Just a few suggestions -- and these are personal choices which might not align with your setup.
I find it a lot easier to separate the SSL config items away from BW and just run BW through an nginx reverse proxy.  

In terms of automating renewals, if you obtain your certs using acme.sh  it has an option for automatic renewal.  By default acme.sh writes a line item into the root crontab which attempts to renew certs every night or once a day.  Personally I went ahead and kind of converted the cronjob into a systemd timer which does the same thing.  Nothing wrong with cron however I like playing with systemd timers as well. The beauty of this setup is kind of a set it once and forget structure.

**Comment by e-alfred** [comment] 2020-06-23 22:48
@kevdogg Did you setup anything else for acme.sh with Bitwarden? How does Bitwarden get restarted using acme.sh?

**Comment by kevdogg** [comment] 2020-06-23 23:02
@e-alfred - Can you describe your setup?  Do you have SSL certs on your reverse proxy and/or with bitwarden_rs?  In other words -- is your reverse proxy SSL terminating or SSL terminating and re-encrypting?  With acme.sh, any service that depends on an SSL certificate, needs to be restarted when the certificates are renewed usually via a post-hook command.  With docker this could be through a "docker restart <bitwarden_container_name>".  You need to be mindful however that the acme.sh post-hook command is run as the root user since likely restarting docker services is going to need to done as root.  If you need multiple services, I would stick all the commands within a shell script file and just call the shell script file to execute after the certificates are renewed.

**Comment by djsmith85** [comment] 2021-08-23 10:27
Closing this issue as it appears the originally posted problem has been resolved. If this happens again or continues to be an issue please feel free to re-open this issue and let us know, along with any additional detail to assist with reproduction and root cause analysis.

**Closed by djsmith85** 2021-08-23 10:27 UTC
