### ISSUE TITLE
Unable to migrate MySQL database after updating to >= 2024.1

### ISSUE THREAD

**Issue by TotallyMonica** [bitwarden/server#3871] opened 2024-03-04 20:00 UTC
### Steps To Reproduce

1. Set up Unified instance on <= 2023.12 utilizing a MySQL connector
2. Pull a >= 2024.1 image
3. Observe admin process crashing due to database migration issues

### Expected Result

Database gets successfully migrated, with the container working successfully

### Actual Result

Admin process perpetually crashes and relaunches upon unsuccessful DB migration

### Screenshots or Videos

Relevant logs
[docker-logs.txt](https://github.com/bitwarden/server/files/14486514/docker-logs.txt)
[identity.log](https://github.com/bitwarden/server/files/14486553/identity.log)
[notifications.log](https://github.com/bitwarden/server/files/14486555/notifications.log)
[api.log](https://github.com/bitwarden/server/files/14486556/api.log)
[admin.log](https://github.com/bitwarden/server/files/14486557/admin.log)

### Additional Context

When working with a fresh database, this issue is not present, this appears to be exclusive to updating from a 2023.X to 2024.X installation

### Githash Version

b3a6bf5a-dirty

### Environment Details

- Operating System: Ubuntu 22.04 (Docker host), Debian 12 (MySQL Server)
- Docker: 24.0.5
- Hardware: Linode Shared CPU 4GB

### Database Image

External MariaDB 10.11.6
Known buggy versions: 2024.1-beta, 2024.2-beta
Last known working: 2023.12-beta

### Issue-Link

https://github.com/bitwarden/server/issues/2480

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Greenderella** [comment] 2024-03-11 15:53
Hi there!

Thank you for your report, it seems like it is a duplicate of https://github.com/bitwarden/server/issues/3651

You can attempt to drop the conflicting columns manually, following these steps: https://github.com/bitwarden/server/issues/3651#issuecomment-1900668445

This issue will now be closed.

Thanks!

**Closed by Greenderella** 2024-03-11 15:53 UTC
Labels: bug, bw-unified-deploy
