### ISSUE TITLE
Bitwarden Identity failing with 'Event_Create' missing parameter

### ISSUE THREAD

**Issue by Philipose** [bitwarden/server#1535] opened 2021-08-24 15:31 UTC
## Describe the Bug

bitwarden-identity is returning an error for new logins

`Procedure or function 'Event_Create' expects parameter '@ProviderId', which was not supplied.`

I was using the latest tag to keep up with my slightly custom config. But since I had to roll back from 1.42.x, it has been problematic. I rolled back based on the guidance from this #1528 . Existing sessions will still work and sync. New sessions will error out with the failure listed above.

I have also tried running updatedb but have had no success solving the issue

## Steps To Reproduce

1. Upgrade self-hosted using ":latest" or "1.42.x" tags
2. Downgrade self-hosted to 1.41.6.
3. Attempt a new login

## Expected Result

Successfully login either through web or extension/app

## Actual Result

A longer failure that begins with 

`Procedure or function 'Event_Create' expects parameter '@ProviderId', which was not supplied.`

I can pull a more complete stack trace if necessary.

This failure occurs on the last step of login (explained in additional comments)

## Environment

- Operating system: Debian 10
- Build Version: 1.41.6
- Self Hosted: true
- Environment: Docker
- Hardware: Proxmox VM, 96GB RAM, 16-cores

## Additional Context

As luck would have it, my premium expired as I was trying to figure out that issue so until I get this sorted I'm SOL on quite a bit.

On web: if logging in with an account that has MFA enabled, I get to the MFA page before it fails. If the account does not have MFA it fails on the main login screen.

On safari extension: it fails right on the first login page. I think I trusted the extension once before though.

**Comment by eliykat** [comment] 2021-08-24 22:30
I think the problem is that the database migration scripts work in one direction only. You've rolled back the server code to v1.41.6 but the database schema and stored procedures are still on v1.42.x. I'm not aware of any method that we provide to downgrade the database schema. I assume maybe the other commenters in that thread had a backup they could restore. (I'll double check to make sure I'm not missing anything though.)

It may be easier to solve the original problem. Do the instructions [here](https://github.com/bitwarden/server/issues/1528#issuecomment-9027564380) help?

**Comment by eliykat** [comment] 2021-08-24 22:38
The problem is that our database migration scripts only work in one direction. You've downgraded your server code to 1.41.6 but your database schema and stored procedures are still on 1.42.x. The database is expecting an argument that your server isn't providing.

You could:
* try to resolve the original issue. Does [this suggestion](https://github.com/bitwarden/server/issues/1528#issuecomment-902756438) help as a workaround?
* try restoring a nightly backup of your db container - see information here: https://bitwarden.com/help/article/backup-on-premise/.

If you've got issues with your premium subscription or need support generally, you can contact our Customer Success team here: www.bitwarden.com/contact. You'll generally get faster support than here on Github, which we use for tracking bugs rather than support issues.

**Comment by eliykat** [comment] 2021-08-25 02:49
I'm going to close this because it's not a defect that we can fix. If you're having issues with the original bug, please post in #1528. If you need assistance downgrading or managing your self-hosted deployment, please contact our Customer Success team using the form in my previous post. Thanks!

**Closed by eliykat** 2021-08-25 02:49 UTC

**Comment by Philipose** [comment] 2021-08-25 12:48
Sorry it looks like I must of not made it to the bottom of that ticket. Thank you for pointing that out. I've updated the cert by hand and it works on latest again. I appreciate the assistance!
