### ISSUE TITLE
Mssql dockerfile points to CU11 not CU12 bricking Kernel 6.7+ support

### ISSUE THREAD

**Issue by lateparty** [bitwarden/server#3908] opened 2024-03-17 06:30 UTC
### Steps To Reproduce

To reproduce try install  2024.2.3 on any distro with kernel 6.7+ 

### Expected Result

Working database and Bitwarden self hosted server instance

### Actual Result

Broken mssql database connection

### Additional Context

Per this issue https://github.com/microsoft/mssql-docker/issues/868 CU12 for mssql2022 is out the issue is fixed upstream now. Accordingly, please update bitwarden.sh. A 2024.2.4 emergency release would be greatly appreciated.

I would expect at a minimum the from entry here needs to updated to CU12 but I am not sure which other elements and what testing is necessary.

https://github.com/bitwarden/server/blob/main/util/MsSql/Dockerfile 

### Build Version

2024.2.3

### Environment

Self-Hosted

### Environment Details

Arch Linux 

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by lateparty** [comment] 2024-03-17 11:26
Seems to be working now. Not sure what happened / was happening!

**Comment by lateparty** [comment] 2024-03-17 11:36
Never mind premature close. I can see that the dockerfile is updated to pull CU12 and was 2 days ago (bad cache for me seeing CU11??) however per this screenshot after I run updateself and update, I still pull down CU11.

reference for versions:
https://learn.microsoft.com/en-us/troubleshoot/sql/releases/sqlserver-2022/build-versions

![IMG_3015](https://github.com/bitwarden/server/assets/20498775/0490fb30-1229-457c-b434-e4123f540657)

![IMG_3016](https://github.com/bitwarden/server/assets/20498775/1bf92237-80c2-476d-bc98-3481809f4ed1)

**Comment by djsmith85** [comment] 2024-03-18 13:02
Duplicate of https://github.com/bitwarden/server/issues/3689

**Comment by djsmith85** [comment] 2024-03-18 13:03
Hi @lateparty this is a duplicate of https://github.com/bitwarden/server/issues/3689 and solved with https://github.com/bitwarden/server/pull/3904.

Currently expecting to release self-host end of the week.

Closing this now.

Kind regards,
Daniel

**Closed by djsmith85** 2024-03-18 13:03 UTC
Labels: bug
