### ISSUE TITLE
Unmatched version number between web and admin portal

### ISSUE THREAD

**Issue by MuadDibIII** [bitwarden/server#2956] opened 2023-05-24 09:40 UTC
### Steps To Reproduce

1. Go to admin portal and check the "Web installed" version number
2. Go to Bitwarden web vault and check the "Version" number on the bottom of the screen

### Expected Result

The two numbers should match

### Actual Result

The web vault number seams older than the Admin's portal web installed one

### Screenshots or Videos

![web](https://github.com/bitwarden/server/assets/5659533/9998c8f2-1bc0-4a14-b7b0-d0ffaa938a32)
![admin](https://github.com/bitwarden/server/assets/5659533/de458434-37be-4a92-996d-e0928b9a4a79)

### Githash Version

568d87eb-dirty

### Environment Details

- Docker on Synology NAS, DSM 7.1.1

### Database Image

mariadb: 10 on Synology NAS

### Issue-Link

https://github.com/bitwarden/server/issues/2480

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by justindbaur** [comment] 2023-05-25 18:37
Hi @MuadDibIII the better wording for this is that it is intended... for now. Due to the way we release the beta tag for unified it's likely that it will run a bit ahead or the standard deployment and the version displayed in the admin portal are that of the standard deployment. Once we release unified for GA it will match the standard deployment versions rather closely. Even though this issue was reopened at my direction yesterday I am going to close this as a duplicate of #2888 since it was opened first and shows the same issue. 

Let me know if you have any more questions though.

**Closed by justindbaur** 2023-05-25 18:37 UTC
Labels: bug, bw-unified-deploy
