### ISSUE TITLE
terminated by SIGABRT (core dumped) while self hosting Unified version bitwarden and mysql

### ISSUE THREAD

**Issue by tjc0726** [bitwarden/server#5042] opened 2024-11-16 03:39 UTC
### Steps To Reproduce

register a user

### Expected Result

sucessfully registered

### Actual Result

get error while register,docker's log says:

2024-11-16 03:08:16,951 WARN exited: admin (terminated by SIGABRT (core dumped); not expected)
2024-11-16 03:08:17,954 INFO spawned: 'admin' with pid 184

### Screenshots or Videos

admin.log says:
```
-- Step 6: Drop the temporary tables
    DROP TEMPORARY TABLE IF EXISTS `TempGroupsAccessAll`;
    DROP TEMPORARY TABLE IF EXISTS `TempUsersAccessAll`;
    DROP TEMPORARY TABLE IF EXISTS `TempUserManagers`;
2024-11-16 03:00:55.975 +00:00 [ERR] Hosting failed to start
MySqlConnector.MySqlException (0x80004005): Statement violates GTID consistency: CREATE TEMPORARY TABLE and DROP TEMPORARY TABLE can only be executed outside transactional context.  These statements are also not allowed in a function or trigger because functions and triggers are also considered to be multi-statement transactions.
   at MySqlConnector.Core.ServerSession.ReceiveReplyAsync(IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/ServerSession.cs:line 894
   at MySqlConnector.Core.ResultSet.ReadResultSetHeaderAsync(IOBehavior ioBehavior) in /_/src/MySqlConnector/Core/ResultSet.cs:line 37
   at MySqlConnector.MySqlDataReader.ActivateResultSet(CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlDataReader.cs:line 130
   at MySqlConnector.MySqlDataReader.InitAsync(CommandListPosition commandListPosition, ICommandPayloadCreator payloadCreator, IDictionary`2 cachedProcedures, IMySqlCommand command, CommandBehavior behavior, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlDataReader.cs:line 483
   at MySqlConnector.Core.CommandExecutor.ExecuteReaderAsync(CommandListPosition commandListPosition, ICommandPayloadCreator payloadCreator, CommandBehavior behavior, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/CommandExecutor.cs:line 56
   at MySqlConnector.MySqlCommand.ExecuteNonQueryAsync(IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlCommand.cs:line 309
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQuery(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQuery(IEnumerable`1 migrationCommands, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.Migrate(DatabaseFacade databaseFacade)
   at Bit.MySqlMigrations.MySqlDbMigrator.MigrateDatabase(Boolean enableLogging, CancellationToken cancellationToken) in /source/util/MySqlMigrations/MySqlDbMigrator.cs:line 30
   at Bit.Admin.HostedServices.DatabaseMigrationHostedService.StartAsync(CancellationToken cancellationToken) in /source/src/Admin/HostedServices/DatabaseMigrationHostedService.cs:line 29
   at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>b__15_1(IHostedService service, CancellationToken token)
   at Microsoft.Extensions.Hosting.Internal.Host.ForeachService[T](IEnumerable`1 services, CancellationToken token, Boolean concurrent, Boolean abortOnFirstException, List`1 exceptions, Func`3 operation)

```

### Build Version

bitwarden unified with latest image

### Environment

Self-Hosted

### Environment Details

Mysql 5.7
ubuntu 22.0.4

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by SergeantConfused** [comment] 2024-11-18 12:53
Hello @tjc0726,

Thank you for your report. This report seems to be a duplicate of this [GitHub report](https://github.com/bitwarden/server/issues/2718). I highly recommend reading that existing thread and if there's anything you'd like to add, such as screenshots or video recordings of the screen, please feel free to add them to that GitHub report.

This report will now be closed as a duplicate.

Thank you again,

**Closed by SergeantConfused** 2024-11-18 12:53 UTC
Labels: bug, bw-unified-deploy
