### ISSUE TITLE
Reported Web Version Discrepancy

### ISSUE THREAD

**Issue by jmcmahel** [bitwarden/server#2146] opened 2022-07-25 22:30 UTC
### Steps To Reproduce

1. Check the Web Installed version on the admin dashboard
2. Run 'docker ps' on the server
3. Compare the bitwarden/web version to the Web Installed version

### Expected Result

The bitwarden/web version from 'docker ps' should match the Web Installed version on the admin dashboard.

### Actual Result

Web Installed shows 2022.6.1 while 'docker ps' shows bitwarden/web:2022.6.2

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/50854322/180883871-a2b33113-d823-4bcd-baaf-6dab402b12d3.png)

### Additional Context

docker ps
CONTAINER ID   IMAGE                              COMMAND            CREATED         STATUS                   PORTS                                                                                    NAMES
5cfe1900db5c   bitwarden/nginx:2022.6.2           "/entrypoint.sh"   2 minutes ago   Up 2 minutes (healthy)   80/tcp, 0.0.0.0:80->8080/tcp, :::80->8080/tcp, 0.0.0.0:443->8443/tcp, :::443->8443/tcp   bitwarden-nginx
768b8627dd14   bitwarden/admin:2022.6.2           "/entrypoint.sh"   2 minutes ago   Up 2 minutes (healthy)   5000/tcp                                                                                 bitwarden-admin
606ad4d6fd0d   bitwarden/mssql:2022.6.2           "/entrypoint.sh"   2 minutes ago   Up 2 minutes (healthy)                                                                                            bitwarden-mssql
8834ab70469e   bitwarden/identity:2022.6.2        "/entrypoint.sh"   2 minutes ago   Up 2 minutes (healthy)   5000/tcp                                                                                 bitwarden-identity
b3fdc2b00614   bitwarden/sso:2022.6.2             "/entrypoint.sh"   2 minutes ago   Up 2 minutes (healthy)   5000/tcp                                                                                 bitwarden-sso
38a4030fb3b5   bitwarden/events:2022.6.2          "/entrypoint.sh"   2 minutes ago   Up 2 minutes (healthy)   5000/tcp                                                                                 bitwarden-events
898de4c5e4d2   bitwarden/attachments:2022.6.2     "/entrypoint.sh"   2 minutes ago   Up 2 minutes (healthy)                                                                                            bitwarden-attachments
9d022f01a65a   bitwarden/notifications:2022.6.2   "/entrypoint.sh"   2 minutes ago   Up 2 minutes (healthy)   5000/tcp                                                                                 bitwarden-notifications
ff78ab89feb2   bitwarden/web:2022.6.2             "/entrypoint.sh"   2 minutes ago   Up 2 minutes (healthy)                                                                                            bitwarden-web
2c9daf6c66fa   bitwarden/api:2022.6.2             "/entrypoint.sh"   2 minutes ago   Up 2 minutes (healthy)   5000/tcp                                                                                 bitwarden-api
22bc773477ca   bitwarden/icons:2022.6.2           "/entrypoint.sh"   2 minutes ago   Up 2 minutes (healthy)   5000/tcp                                                                                 bitwarden-icons

### Build Version

2022.6.2

### Environment

Self-Hosted

### Environment Details

- Operating System: RHEL 8.6
- Docker Engine: 20.10.17
- Docker Compose: 2.6.0

**Comment by dbosompem** [comment] 2022-07-26 11:01
Hi @jmcmahel , thank you for bringing this up. We will reproduce this at our end, and take a look at it. Appreciate this!

**Comment by Ayitaka** [comment] 2022-07-27 20:37
See also [this issue on the self-hosted repository](https://github.com/bitwarden/self-host/issues/35)

**Comment by jmcmahel** [comment] 2022-08-04 00:02
![image](https://user-images.githubusercontent.com/50854322/182734510-8d1a8f34-f199-4982-b529-ddb7cfb9aeaf.png)

The admin dashboard is now showing 2022.8.0 as the latest version, while bitwarden/server shows 2022.6.2 as the latest.

**Comment by Ayitaka** [comment] 2022-08-04 00:43
> ![image](https://user-images.githubusercontent.com/50854322/182734510-8d1a8f34-f199-4982-b529-ddb7cfb9aeaf.png)
> 
> The admin dashboard is now showing 2022.8.0 as the latest version, while bitwarden/server shows 2022.6.2 as the latest.

This is because the [Bitwarden/server](https://github.com/bitwarden/server) version was bumped to 2022.8.0, for the new month. But that is not the [Bitwarden/self-host](https://github.com/bitwarden/self-host). self-host has its own versions, which always lag behind Bitwarden/server so that a release can be tested before being pushed to self-host clients.

Having said that, maybe the admin dashboard for self-host should only show the latest version for self-host, not for server, because that can be confusing... case in point.

**Comment by Hinton** [comment] 2022-08-05 12:07
We've improved the version detection in this release, and it should no longer announce a newer version before it is released. https://github.com/bitwarden/server/pull/2006

**Comment by adam-olson** [comment] 2022-08-15 22:09
Looks like the version #'s might be backwards, Server version appears where the web version is and vis versa, 
![image](https://user-images.githubusercontent.com/45909856/184726793-095d26e0-c135-405a-892c-232fb4f67edc.png)

**Comment by Hinton** [comment] 2022-08-23 09:02
Thanks for letting us know @adam-olson. This will be resolved in the next release.

**Closed** 2022-08-23 09:31 UTC
Labels: bug
