### ISSUE TITLE
Server and web server version mismatched 

### ISSUE THREAD

**Issue by iguys** [bitwarden/server#2986] opened 2023-05-31 15:31 UTC
### Steps To Reproduce

4. Click on '...'

### Expected Result

Server and web version should be matched

### Actual Result

Dashboard
Welcome to the Bitwarden System Administration
Portal.
VERSION
Server Installed
2023.5.0 A
Server Latest
2023.4.3
Web Installed
Unable to fetch installed version A
Web Latest
2023.4.2

### Screenshots or Videos

![IMG_6617](https://github.com/bitwarden/server/assets/96700289/410d0781-7a04-448e-9515-71479afa34b3)

### Githash Version

1202a670-dirty

### Database Image

SQLite 

### Issue-Link

https://github.com/bitwarden/server/issues/2480

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by justindbaur** [comment] 2023-05-31 20:28
Duplicate of #2888

**Closed by justindbaur** 2023-05-31 20:28 UTC
Labels: bug, bw-unified-deploy
