### ISSUE TITLE
Unhandled Server Error when Creating User

### ISSUE THREAD

**Issue by freshjwarren** [bitwarden/server#393] opened 2018-11-13 05:51 UTC
I have a hosted vault. I have been using the Chrome extension on Linux for a while without issue. Recently (maybe after upgrading to Ubuntu 18.04?) I have started receiving this error every time I try to manually create an item:

1. Go to Add Item
2. Enter username and password
3. Click Save 
4. Result is a pop-up message:
An error has occured.
An unhandled server error has occured.
5. The Add Item window does not close and the item has not been added to my vault

The extension can successfully save a new login that it observes.

**Comment by jw173** [comment] 2018-11-13 16:02
Sorry, not self-hosted; you-hosted.

How does logging work for Chrome extensions? Do I need to turn something on?

**Comment by kspearrin** [comment] 2018-11-13 16:05
Can you try logging out and back in to see if that resolves any issues?

**Comment by Vaelek** [comment] 2018-12-01 06:08
Bone stock install, changed only the ports to play nice (to a degree that's debatable) with existing webserver. Same issue, here is the error

```
2018-12-01 06:06:41.993 +00:00 [Error] Cannot open database "vault" requested by the login. The login failed.
Login failed for user 'sa'.
System.Data.SqlClient.SqlException (0x80131904): Cannot open database "vault" requested by the login. The login failed.
Login failed for user 'sa'.
   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.WaitForPendingOpen()
--- End of stack trace from previous location where exception was thrown ---
   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in C:\projects\dapper\Dapper\SqlMapper.Async.cs:line 419
   at Bit.Core.Repositories.SqlServer.UserRepository.GetByEmailAsync(String email) in /home/bitwarden/Projects/bitwarden/core/src/Core/Repositories/SqlServer/UserRepository.cs:line 32
   at Bit.Core.Identity.UserStore.FindByEmailAsync(String normalizedEmail, CancellationToken cancellationToken) in /home/bitwarden/Projects/bitwarden/core/src/Core/Identity/UserStore.cs:line 54
   at Bit.Core.Identity.UserStore.FindByNameAsync(String normalizedUserName, CancellationToken cancellationToken) in /home/bitwarden/Projects/bitwarden/core/src/Core/Identity/UserStore.cs:line 78
   at Microsoft.AspNetCore.Identity.UserManager`1.FindByNameAsync(String userName)
   at Microsoft.AspNetCore.Identity.UserValidator`1.ValidateUserName(UserManager`1 manager, TUser user, ICollection`1 errors)
   at Microsoft.AspNetCore.Identity.UserValidator`1.ValidateAsync(UserManager`1 manager, TUser user)
   at Microsoft.AspNetCore.Identity.UserManager`1.ValidateUserAsync(TUser user)
   at Microsoft.AspNetCore.Identity.UserManager`1.CreateAsync(TUser user)
   at Microsoft.AspNetCore.Identity.UserManager`1.CreateAsync(TUser user, String password)
   at Bit.Core.Services.UserService.RegisterUserAsync(User user, String masterPassword, String token, Nullable`1 orgUserId) in /home/bitwarden/Projects/bitwarden/core/src/Core/Services/Implementations/UserService.cs:line 236
   at Bit.Api.Controllers.AccountsController.PostRegister(RegisterRequestModel model) in /home/bitwarden/Projects/bitwarden/core/src/Api/Controllers/AccountsController.cs:line 69
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.AwaitableResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextExceptionFilterAsync()
```

**Comment by Svarto** [comment] 2019-01-13 15:44
I have the same error as @Vaelek 

Anyone found a solution?

**Comment by djsmith85** [comment] 2021-12-13 14:11
Hi @freshjwarren, it appears we've not heard from you about this issue in some time. While we are now closing this issue, if it continues to be a problem please feel free to re-open this issue and provide any further information that may be helpful in reproducing the problem or helping you further.

@Vaelek This seems to be a different issue, which I assume has been solved, due to the age of this ticket. If this is still an issue, please open a new issue.

**Closed by djsmith85** 2021-12-13 14:11 UTC
