### ISSUE TITLE
Enterprise Trial License Upload results in "Invalid License"

### ISSUE THREAD

**Issue by BRsmover** [bitwarden/server#919] opened 2020-09-08 14:44 UTC
I'm self hosting Bitwarden. After I made a trial license for Bitwarden Enterprise and downloaded the license file, I tried creating a new organisation via _Settings > Organisations_ on my installation.

When I submit the uploaded license I get the error message "An error occurred - Invalid license". Looking at the network tab in the developer tools, I see that the request failed with the status 400.

The installation id is correct, I double checked that. The value for "SelfHost" is _true_ and the "Trial" value is also _true_ in the downloaded .json file

Restarting Bitwarden didn't help either.

Does anybody have an idea what the reason for that might be and/ or how I can fix this?

Edit: I tried to find some logs that could give more information but I couldn't find any that seemed useful.

**Comment by kspearrin** [comment] 2020-09-09 21:08
@BRsmover , can you please try updating to the latest docker images that we just released? They should now support your trial license. Just run:

```
./bitwarden.sh updateself
./bitwarden.sh update
```

Then upload your trial license.

**Comment by cyayung** [comment] 2020-09-10 06:40
I am on the latest version. I am currently running family but recently bought at 14 seat enterprise license. Tried to upload enterprise trial license (7 days) but gives error:

An error has occurred.
Plan not found.

Is it true that I can either run family OR enterprise?

**Comment by swaechter** [comment] 2020-09-10 12:47
@kspearrin I am a coworker of @BRsmover and updated the instance to version 1.37.0. Now the license file works & I can create organizations. So this issue can be closed or changed to cyayungs need.

Thanks for the fast response & release :)

**Comment by cscharf** [comment] 2020-09-10 12:55
Great, thanks @swaechter , glad that's working!

**Comment by cscharf** [comment] 2020-09-10 13:32
> I am on the latest version. I am currently running family but recently bought at 14 seat enterprise license. Tried to upload enterprise trial license (7 days) but gives error:
> 
> An error has occurred.
> Plan not found.
> 
> Is it true that I can either run family OR enterprise?

@cyayung , can you please open a new issue for what you're experiencing? We feel that may be a different issue/root cause and would like to track that apart from this issue here.

**Comment by cscharf** [comment] 2020-09-10 13:37
> I am on the latest version. I am currently running family but recently bought at 14 seat enterprise license. Tried to upload enterprise trial license (7 days) but gives error:
> 
> An error has occurred.
> Plan not found.
> 
> Is it true that I can either run family OR enterprise?

We're still investigating this, which appears to be a different issue.

**Comment by addisonbeck** [comment] 2020-09-10 14:46
@cyayung , would you mind sending a copy of your license to support@bitwarden.com? You should be able to run enterprise or family, that is true. I'd like to take a look at the plan information on your license to troubleshoot.

**Comment by addisonbeck** [comment] 2020-09-14 16:46
I'm going to go ahead and close this one for now, as the original issue is resolved. @cyayung please reopen if you are still seeing this issue & have sent over that license file. Thanks!

**Closed by addisonbeck** 2020-09-14 16:46 UTC
