### ISSUE TITLE
Authentication with Azure AD

### ISSUE THREAD

**Issue by RafaelHGBotelho** [bitwarden/server#1146] opened 2021-02-17 14:01 UTC
I noticed in a post that LDAP does not have integration of passwords to login to BitWarden.

I did some tests with Azure AD and saw that it only sends an invitation to users, is it possible to integrate authentication with AD credentials as well?

Thank you!

**Comment by tgreer-bw** [comment] 2021-02-17 14:02
Indeed it is!

- https://bitwarden.com/help/login-with-sso/
- https://bitwarden.com/help/article/saml-azure/

**Comment by clayadams5226** [comment] 2021-03-26 04:13
Closing this issue as it appears the originally posted problem has been resolved. If this happens again or continues to be an issue please feel free to re-open this issue and let us know, along with any additional detail to assist with reproduction and root cause analysis.

**Closed by clayadams5226** 2021-03-26 04:13 UTC
