### ISSUE TITLE
SMTP issues with gmail

### ISSUE THREAD

**Issue by regeneratorre4** [bitwarden/server#2949] opened 2023-05-20 19:39 UTC
### Steps To Reproduce

Set up gmail as the SMTP provider in the unified dockers settings.env file under the Mail section

Once that is setup and you have a proper app password set up/no issues with authentication, go to your bitwarden server address and try to setup and email as the secondary 2FA/verify an email or create a new account. Some emails will go through, but one specific email that gets blocked by gmail 100% of the time is the "Your Two-step Login Verification Code" emails. The email gets "sent", but is intercepted by google's automation and you get a reply from  mailer-daemon@googlemail.com stating "Message blocked",

The response was:

Message rejected. See https://support.google.com/mail/answer/69585 for more information. 

___

Now just testing this out with a random email, there is something "phissy/spammy" about the subject line of the email which causes the email to get picked up based on my testing. If you try and send an email manually from the gmail UI with the subject of "Your Two-step Login Verification Code", it will get rejected as well. And you can even send the original content of the 2FA email, but with a different subject line which will bypass google's automation. 

___

Now I'm not a dev or anything but I think we will need to change the subject line of the email bitwarden sends out to bypass the false positive gmail is catching on

### Expected Result

email not getting blocked

### Actual Result

email getting blocked

### Additional Context

Works fine when using yahoo as SMTP, but who wants to use yahoo? Using outlook has some additional problems not related to bitwarden

### Githash Version

8d9ca424-dirty

### Environment Details

OS: UnRaid 6.11.5
Running in docker
i9-10900, 64GB RAM

### Database Image

self included sqllite DB in the unified docker image

### Issue-Link

https://github.com/bitwarden/server/issues/2480

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by regeneratorre4** [comment] 2023-05-21 19:45
SMTP providers that work:
- yahoo (ew)
- AWS SES (yummy)

**Comment by djchateau** [comment] 2023-05-23 03:02
Hey there,

I am unable to reproduce this issue, it has been escalated for further investigation. If you have more information that can help us, please add it below. 

Thanks!

**Comment by regeneratorre4** [comment] 2023-05-23 03:32
> Hey there,
> 
> I am unable to reproduce this issue, it has been escalated for further investigation. If you have more information that can help us, please add it below.
> 
> Thanks!

To repro the issue the simplest way do the following:

Go to your gmail account via the gmail UI (mail.google.com)
Send an email with the subject line “Your Two-step Login Verification Code” to any email of choice. The body of the email is irrelevant, you can put anything, or nothing.
Your email will get blocked by gmail and you will receive a response from [mailer-daemon@googlemail.com](mailto:mailer-daemon@googlemail.com) stating “Message blocked.. Message rejected…”

**Comment by GieltjE** [comment] 2023-05-24 09:43
Probably the same issue as with O365, legacy authentication has been disabled.
Would require oauth and preferably app integration (with O365 at least).

**Comment by justindbaur** [comment] 2023-05-25 19:25
@regeneratorre4 I just tried your reproduction steps of sending an email from Gmail UI and the email went through just fine. Since there are SMTP providers that do work for you and seemingly the fix being proposed would just be changing the subject I think I am going to be closing this as not planned.

**Closed by justindbaur** 2023-05-25 19:25 UTC
Labels: bug, bw-unified-deploy
