### ISSUE TITLE
Secure note disappeared without trace

### ISSUE THREAD

**Issue by elo613** [bitwarden/server#1035] opened 2020-12-08 23:24 UTC
I am a free member to Bitwarden

I tried to add an attachment to a secure note but was told I need to be a premium member to do this. Following this, I lost this note, and another note
They weren't in the bin. They weren't in my vault. They couldn't be searched for. I have no idea what happened to them. I did not delete them because if I had they would have been in the bin.

Any ideas?

Edit: I don't know what happened...but the secure note reappeared in the search box after a minute or so....

This was still concerning and I'm not sure if this is me being inept or an actual bug

**Comment by clayadams5226** [comment] 2021-01-08 04:26
Hi @elo613, have you encountered this issue again? We've been unable to reproduce it on ourside. For now, I'm going to close this ticket but feel free to re-open or create a new one should the problem present itself again.

**Closed by clayadams5226** 2021-01-08 04:26 UTC
