### ISSUE TITLE
MSSQL access denied

### ISSUE THREAD

**Issue by MartB** [bitwarden/server#531] opened 2019-07-16 14:09 UTC
```
2019-07-16 14:07:59.98 Server      Error: 17113, Severity: 16, State: 1.
2019-07-16 14:07:59.98 Server      Error 5(Access is denied.) occurred while opening file '/var/opt/mssql/data/master.mdf' to obtain configuration information at startup. An invalid startup option might have caused the error. Verify your startup options, and correct or remove them if necessary.
```

after updating docker i get this on every start.

docker is Docker version 19.03.0-rc3, build 27fcb77

What is wrong here?

Edit:
I transfered my entire database into the docker volume by setting `database_docker_volume: true` and then copying my bwdata/mssql files over one by one.

This got my instance back up and running but i wonder if more people will run into this issue as the new docker version become available.

**Comment by steveaggie** [comment] 2019-07-31 19:13
I have this issue too after updating my Ubuntu packages.  Can you provide more detail?  I'm a bit of a noob.

**Comment by MartB** [comment] 2019-08-01 16:13
Hey @steveaggie,

`641dd0222693` is my mssql container id
`/opt/bitwarden/` is my install path

I did the following:
1) set `database_docker_volume: true` to `true` in `/opt/bitwarden/bwdata/config.yml`

```
docker cp /opt/bitwarden/bwdata/mssql/data/master.mdf                                                         641dd0222693:/var/opt/mssql/data/master.mdf                                                  
docker cp /opt/bitwarden/bwdata/mssql/data/mastlog.ldf                                                        641dd0222693:/var/opt/mssql/data/mastlog.ldf                                                 
docker cp /opt/bitwarden/bwdata/mssql/data/modellog.ldf                                                       641dd0222693:/var/opt/mssql/data/modellog.ldf                                                
docker cp /opt/bitwarden/bwdata/mssql/data/model.mdf                                                          641dd0222693:/var/opt/mssql/data/model.mdf                                                   
docker cp /opt/bitwarden/bwdata/mssql/data/msdbdata.mdf                                                       641dd0222693:/var/opt/mssql/data/msdbdata.mdf                                                
docker cp /opt/bitwarden/bwdata/mssql/data/msdblog.ldf                                                        641dd0222693:/var/opt/mssql/data/msdblog.ldf                                                 
docker cp /opt/bitwarden/bwdata/mssql/data/tempdb.mdf                                                         641dd0222693:/var/opt/mssql/data/tempdb.mdf                                                  
docker cp /opt/bitwarden/bwdata/mssql/data/templog.ldf                                                        641dd0222693:/var/opt/mssql/data/templog.ldf                                                 
docker cp /opt/bitwarden/bwdata/mssql/data/vault_log.ldf                                                      641dd0222693:/var/opt/mssql/data/vault_log.ldf                                               
docker cp /opt/bitwarden/bwdata/mssql/data/vault.mdf                                                          641dd0222693:/var/opt/mssql/data/vault.mdf  
```

**Comment by KnappeGEIL** [comment] 2019-10-22 09:05
@MartB Where on the container do I need to copy the files?

**Comment by MartB** [comment] 2019-10-29 09:34
I updated the formatting of the above commands, you should find what you were looking for there @KnappeGEIL

**Comment by kromonos** [comment] 2020-02-22 13:09
> Hey @steveaggie,
> 
> `641dd0222693` is my mssql container id
> `/opt/bitwarden/` is my install path
> 
> I did the following:
> 
>     1. **BACKUP** your file storage in bwdata/*
> 
>     2. set `database_docker_volume: true` to `true` in `/opt/bitwarden/bwdata/config.yml`
> 
>     3. restart bitwarden and wait until it started
> 
>     4. stop it again
> 
>     5. Copy the files over to the docker container
> 
> 
> ```
> dockercp /opt/bitwarden/bwdata/mssql/data/master.mdf    641dd0222693:/var/opt/mssql/data/master.mdf
> dockercp /opt/bitwarden/bwdata/mssql/data/mastlog.ldf   641dd0222693:/var/opt/mssql/data/mastlog.ldf
> dockercp /opt/bitwarden/bwdata/mssql/data/modellog.ldf  641dd0222693:/var/opt/mssql/data/modellog.ldf
> dockercp /opt/bitwarden/bwdata/mssql/data/model.mdf     641dd0222693:/var/opt/mssql/data/model.mdf
> dockercp /opt/bitwarden/bwdata/mssql/data/msdbdata.mdf  641dd0222693:/var/opt/mssql/data/msdbdata.mdf
> dockercp /opt/bitwarden/bwdata/mssql/data/msdblog.ldf   641dd0222693:/var/opt/mssql/data/msdblog.ldf
> dockercp /opt/bitwarden/bwdata/mssql/data/tempdb.mdf    641dd0222693:/var/opt/mssql/data/tempdb.mdf
> dockercp /opt/bitwarden/bwdata/mssql/data/templog.ldf   641dd0222693:/var/opt/mssql/data/templog.ldf
> dockercp /opt/bitwarden/bwdata/mssql/data/vault_log.ldf 641dd0222693:/var/opt/mssql/data/vault_log.ldf
> dockercp /opt/bitwarden/bwdata/mssql/data/vault.mdf     641dd0222693:/var/opt/mssql/data/vault.mdf
> ```
> 
>     1. start it again and everything should be running

Big thanks. That saves my day today!

**Comment by Utopism** [comment] 2020-06-06 14:38
Hi all,
I have the same issue, this workaround can give back access to the passwords, but this does not give an explanation of the reason for the error message.

**Comment by elrondvega** [comment] 2021-08-23 14:42
I came across this that said it was related to filesystem format.

https://community.bitwarden.com/t/mssql-keeps-restarting/945/10

**Comment by djsmith85** [comment] 2021-12-16 11:51
Closing this issue as it appears the originally posted problem has been resolved. If this happens again or continues to be an issue please feel free to re-open this issue and let us know, along with any additional detail to assist with reproduction and root cause analysis.

**Closed by djsmith85** 2021-12-16 11:51 UTC
