### ISSUE TITLE
Problem CentOS7

### ISSUE THREAD

**Issue by zJeanMiliodas** [bitwarden/server#579] opened 2019-10-15 14:05 UTC
I am performing the procedure of the installation. But I have a doubt. When I do the installation. I can put anything on this line: Enter the domain name for your Bitwarden instance (eg bitwarden.example.com) :?

Can I also just put the IP VM? Because it just doesn't work.

The problem is that testing on CentOS 7 when I run the "./bitwarden update" command it tells you that the mysql containey is still restarting. VM have 4GB.

I did a test on Ubuntu and the problem is different. When I made the command "./bitwarden update" it gave a message that was successful. However when I access my browser it fails. What do I do?

**Comment by kspearrin** [comment] 2019-10-15 14:07
As stated in the install docs, you need to provide a domain name. 

https://help.bitwarden.com/article/install-on-premise/#configure-your-domain

> If you are serving Bitwarden to the outside world you will need to configure a domain name with DNS records that point to your host machine (ex. bitwarden.example.com). You should configure this domain before beginning your Bitwarden installation.

**Comment by djsmith85** [comment] 2021-08-23 10:26
Hi @zJeanMiliodas, I'm closing this, as @kspearrin has provided a link to the docs and I'm assuming the issue being resolved. 
Please feel free to re-open this issue and let us know, along with any additional detail to assist with reproduction and root cause analysis.

**Closed by djsmith85** 2021-08-23 10:26 UTC
