### ISSUE TITLE
Bitwarden after update to 2024.4.2 config version mismatch

### ISSUE THREAD

**Issue by DanielGerecht** [bitwarden/server#4067] opened 2024-05-08 06:37 UTC
### Steps To Reproduce

./bitwarden.sh updateself
./bitwarden.sh update

ERROR: Version mismatch: file /srv/docker/bitwarden/bwdata/docker/docker-compose.yml specifies version 1 but extension file /srv/docker/bitwarden/bwdata/docker/docker-compose.override.yml uses version 3.0 

### Expected Result

Normal Container Start

### Actual Result

ERROR: Version mismatch: file /srv/docker/bitwarden/bwdata/docker/docker-compose.yml specifies version 1 but extension file /srv/docker/bitwarden/bwdata/docker/docker-compose.override.yml uses version 3.0

and closing of the script

### Screenshots or Videos

![image](https://github.com/bitwarden/server/assets/93123556/debc7dd3-efd2-43fa-9c8f-b1caf933f02a)

### Build Version

2024.4.2

### Environment

Self-Hosted

### Environment Details

-Operating System: Ubuntu 22.04 LTS
-Hardware : VMware Compatibility 19

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment] 2024-05-08 08:01
Duplicate of https://github.com/bitwarden/server/issues/4059

**Closed** 2024-05-08 08:01 UTC
Labels: bug
