### ISSUE TITLE
New Accounts can still be created

### ISSUE THREAD

**Issue by Phoenixfeuer** [bitwarden/server#2291] opened 2022-09-20 21:21 UTC
### Steps To Reproduce

1. Go to '...' /bwdata/env/
2. Edit global.override.env
3. set globalSettings__disableUserRegistration=true

I saved the File and restarted the Server using ./bitwarden.sh restart

### Expected Result

Users are not able to create a new Bitwarden account.

### Actual Result

Users can still create new accounts

### Screenshots or Videos

![UsersCanBeCreated](https://user-images.githubusercontent.com/114026991/191366132-a7f98030-50cc-4275-a358-72cd484e19bc.png)

### Build Version

© 2022 Bitwarden Inc. Version 2022.9.1

### Environment

Self-Hosted

### Environment Details

Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.1 LTS
Release:	22.04
Codename:	jammy
  System load:                      0.26025390625
  Temperature:                      76.5 C

**Comment by justindbaur** [comment] 2022-09-21 11:57
Hi @Phoenixfeuer, with the attached images it is expected behavior, we don't hide the button on the client side but block new registrations on the server side, so unless you are getting around that too this is totally expected. To achieve this we would have to make an additional API call to hide the button which we haven't done yet. #1268 is an existing ticket that is still open and there is a [feature request](https://community.bitwarden.com/t/remove-register-button-on-landing-page-in-case-user-registration-is-disabled/6285) on our community forums for it. So unless you're able to fully create users I am going to close this as a duplicate of #1268. Thanks!

**Closed** 2022-09-21 11:58 UTC
Labels: bug, duplicate
