### ISSUE TITLE
Can't host my own bitwarden in an lxc container

### ISSUE THREAD

**Issue by reschandreas** [bitwarden/server#517] opened 2019-06-16 15:02 UTC
I'm trying to run my own instance of bitwarden inside my lxc container but somehow the virtualization doesn't like it, when running `./bitwarden.sh start` I'm getting the following output.
<img width="779" alt="Screenshot 2019-06-16 at 17 01 38" src="https://user-images.githubusercontent.com/16179620/59565846-7373c700-9058-11e9-86f7-5f8539f01a7e.png">

Does somebody have the same problem like me? Or is there a workaround?

**Comment by kspearrin** [comment] 2019-06-17 11:32
Might be related? https://github.com/bitwarden/server/issues/476

Maybe you could try using a docker volume instead under ./bwdata/config.yml

**Comment by stevefan1999-personal** [comment] 2019-07-06 09:48
Remember to relinquish your AppArmor profile and run Docker in AUFS.
```
lxc.apparmor.profile: unconfined
lxc.cgroup.devices.allow: a
lxc.cap.drop:
```

Please be reminded this would make your LXC container as a glorified chroot.

**Comment by reschandreas** [comment] 2019-07-12 14:50
Sorry for the dumb question, but what are the downsides of `lcx.apparmor.profile: unconfined`?

**Comment by stevefan1999-personal** [comment] 2019-07-13 08:38
@reschandreas Take the analogy of that you are a woman effectively naked without a set of armor

**Comment by JonEllis** [comment] 2020-02-26 13:09
I currently run bitwarden in an LXC container (using LXD on Ubuntu 18.04).
To be able to run docker containers inside an LXC container, I have to enable nesting:

```
config:
  security.nesting: "true"
```

The only minor issue I enounter is that it is unable to use the overlay filesystem, so I end up with a very large VFS directory (31G). I should really work out how to improve this some time...

**Comment by djsmith85** [comment] 2021-11-09 14:14
Closing this issue as it appears the originally posted problem has been resolved. If this happens again or continues to be an issue please feel free to re-open this issue and let us know, along with any additional detail to assist with reproduction and root cause analysis.

**Closed by djsmith85** 2021-11-09 14:14 UTC
