### ISSUE TITLE
On-Prem, Office365 SMTP Relay email config | Errors

### ISSUE THREAD

**Issue by W00glin** [bitwarden/server#481] opened 2019-04-16 13:31 UTC
I am hosting an on-prem instance of BitWarden. I was able to setup and configure docker and install and configure BitWarden. However I am running into an error when attempting to send the verification email, the error is as follows:

`An error has occurred. An unhandled server error has occurred.`

Here is what my current configuration looks like:

`globalSettings__mail__replyToEmail=no-reply@dns_etnry.company_name.org`
`globalSettings__mail__smtp__host=smtp.company_name.org`
`globalSettings__mail__smtp__port=25`
`globalSettings__mail__smtp__ssl=false` 
`globalSettings__mail__smtp__username=`
`globalSettings__mail__smtp__password=`
`globalSettings__disableUserRegistration=false`
`adminSettings__admins=`

I would be happy to include my logs, but I am not sure what logs are relevant.

 The Docker host is an Ubuntu Server 18.04 LTS. This is also my first time really using Docker, so I am by no means an expert and there could be something else going wrong under the hood.

Any idea what could be causing the error?

**Comment by kspearrin** [comment] 2019-04-16 13:47
Error logs should be in `./bwdata/logs/Api`

**Comment by W00glin** [comment] 2019-04-16 13:50
@kspearrin 
Here is the output:
2019-04-16 13:17:40.695 +00:00 [Error] The SMTP server has unexpectedly disconnected.
MailKit.Net.Smtp.SmtpProtocolException: The SMTP server has unexpectedly disconnected.
   at MailKit.Net.Smtp.SmtpStream.ReadAheadAsync(Boolean doAsync, CancellationToken cancellationToken)
   at MailKit.Net.Smtp.SmtpStream.ReadResponseAsync(Boolean doAsync, CancellationToken cancellationToken)
   at MailKit.Net.Smtp.SmtpClient.ConnectAsync(String host, Int32 port, SecureSocketOptions options, Boolean doAsync, CancellationToken cancellationToken)
   at Bit.Core.Services.MailKitSmtpMailDeliveryService.SendEmailAsync(MailMessage message) in /home/appveyor/projects/server/src/Core/Services/Implementations/MailKitSmtpMailDeliveryService.cs:line 82
   at Bit.Core.Services.HandlebarsMailService.SendVerifyEmailEmailAsync(String email, Guid userId, String token) in /home/appveyor/projects/server/src/Core/Services/Implementations/HandlebarsMailService.cs:line 47
   at Bit.Core.Services.UserService.SendEmailVerificationAsync(User user) in /home/appveyor/projects/server/src/Core/Services/Implementations/UserService.cs:line 449
   at Bit.Api.Controllers.AccountsController.PostVerifyEmail() in /home/appveyor/projects/server/src/Api/Controllers/AccountsController.cs:line 147
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.AwaitableResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextExceptionFilterAsync()

**Comment by computeralex92** [comment] 2019-04-23 18:07
I think the problem is the disabled SSL:

```
globalSettings__mail__smtp__port=25
globalSettings__mail__smtp__ssl=false
```

Afaik Office 365 is forcing SSL for the SMTP Relay, so you should try to set SSL to true and maybe change the port to 587.

**Comment by W00glin** [comment] 2019-04-24 13:40
> 
> 
> I think the problem is the disabled SSL:
> 
> ```
> globalSettings__mail__smtp__port=25
> globalSettings__mail__smtp__ssl=false
> ```
> 
> Afaik Office 365 is forcing SSL for the SMTP Relay, so you should try to set SSL to true and maybe change the port to 587.

BitWarden sent me an email the other day saying I should do the same change. I made the changes to the SSL global variable to true and changed the port. Still getting the same unhandled server error.

**Comment by fatalglitch** [comment] 2019-05-01 18:27
Office 365 doesn't allow SMTP/s connections unless you setup a trusted connector inside your O365 exchange setup. You will need to define your connector and setup the trust based on the options provided by Microsoft. See the article below:

https://docs.microsoft.com/en-us/exchange/mail-flow-best-practices/how-to-set-up-a-multifunction-device-or-application-to-send-email-using-office-3

**Comment by djsmith85** [comment] 2021-08-23 10:34
Hi @W00glin, it looks like @computeralex92 and @fatalglitch have provided viable solutions for the issue you're experiencing. Closing this now, but please feel free to re-open this issue and let us know, along with any additional detail to assist with reproduction and root cause analysis.

**Closed by djsmith85** 2021-08-23 10:34 UTC
