### ISSUE TITLE
404 Not found when file attachment download

### ISSUE THREAD

**Issue by baek-sang** [bitwarden/server#1413] opened 2021-06-25 16:00 UTC
## Describe the Bug

#1367 
Add 2 line global.override.env and restart
```
globalSettings__attachment__baseDirectory=/etc/bitwarden/core/attachments
globalSettings__attachment__baseUrl=https://site.domain/attachments
```
1. 404 not found error when downloading previously uploaded files.
2. New file upload and download is no problem.

Not exactly, My guess was that there was only `bwdata/core/attchments` 
and it seems that  `bwdata/core/attachments` was added. 
Diff is "**a**", attchment and att[**a**]chments

## Steps To Reproduce

1. HTTP GET to 'https://site.domain/attachments/rand-string~/rand-string~'
4. Validate response has '404 Not found'

## Expected Result
Downloaded file

## Actual Result
404 Not found when previously uploaded file 

## Environment

- Operating system: CentOS 8.4
- Build Version: 1.41.3
- Self Hosted: true
- Environment: Docker
- Hardware: VPS, AMD Epyc 2gen 4GB RAM

**Comment by baek-sang** [comment] 2021-06-26 01:07
Temporary fix
`cp -r bwdata/attchments bwdata/attachments`

What's different `attchments` and `attachments` directory?
If no more using `attchments` directory, when updated need to delete `attchments' directory and moving to `attachments' directory.

**Comment by eliykat** [comment] 2021-06-27 21:26
I'll close this issue because it appears to be a duplicate of #1367. Please direct any discussion to that issue report.

This issue will be fixed in the upcoming release.

**Closed by eliykat** 2021-06-27 21:26 UTC
