### ISSUE TITLE
Bitwarden 2024.5.0 unable to start - docker-compose.yml is invalid

### ISSUE THREAD

**Issue by keithellis74** [bitwarden/server#4130] opened 2024-05-26 22:12 UTC
### Steps To Reproduce

1. Bitwarden updated via cronscript as per documentation
2. Bitwarden fails to start - docker-compose.yml errors
3. Uninstalled Bitwarden ```./bitwarden.sh uninstall``` removing ```bwdata``` directory 
4. Followed the Docker removal instructions here: https://docs.docker.com/engine/install/ubuntu/#uninstall-old-versions
5. Completed clean install of Bitwarden on Ubuntu following the instructions here: https://bitwarden.com/help/install-on-premise-linux/

### Expected Result

Bitwarden starting as per documentation

### Actual Result

`bitwarden@vps786900:/opt/bitwarden$ ./bitwarden.sh start
 _     _ _                         _            
| |__ (_) |___      ____ _ _ __ __| | ___ _ __  
| '_ \| | __\ \ /\ / / _` | '__/ _` |/ _ \ '_ \ 
| |_) | | |_ \ V  V / (_| | | | (_| |  __/ | | |
|_.__/|_|\__| \_/\_/ \__,_|_|  \__,_|\___|_| |_|

Open source password management solutions
Copyright 2015-2024, 8bit Solutions LLC
https://bitwarden.com, https://github.com/bitwarden

===================================================

bitwarden.sh version 2024.5.0
Docker version 26.1.3, build b72abbb
docker-compose version 1.25.3, build d4d1b42b

ERROR: The Compose file '/opt/bitwarden/bwdata/docker/docker-compose.yml' is invalid because:
Unsupported config option for networks: 'default'
Unsupported config option for services: 'web'
ERROR: The Compose file '/opt/bitwarden/bwdata/docker/docker-compose.yml' is invalid because:
Unsupported config option for services: 'api'
Unsupported config option for networks: 'default'`

### Additional Context

I have totally erased by Bitwarden install and re-installed following the Docker install and Bitwarden install instructions. I am unable to start Bitwarden, how can I resolve this please.

### Build Version

2024.5.0

### Environment

Self-Hosted

### Environment Details

Ubuntu 22.04.4 LTS VPS
2GB Ram
40GB hard drive

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by daniellbw** [comment] 2024-05-27 10:10
Hi @keithellis74 ,

I attempted to reproduce your issue and was unable to do so. I think your error could have its origin in a 

This is a duplicate of #4078 

Could you run `which docker-compose` and then if this exists then please delete this and try again.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!

**Closed by daniellbw** 2024-05-27 10:10 UTC
Labels: bug

**Comment by joxxxx** [comment] 2024-05-27 13:42
I had the exact same problem and removing `/usr/local/bin/docker-compose` did the trick ! Thanks a lot !
