### ISSUE TITLE
Bad substitution

### ISSUE THREAD

**Issue by MrHallway0** [bitwarden/server#1405] opened 2021-06-23 04:53 UTC
## Describe the Bug

I created a script to install Bitwarden for me but when I run it I get this:
```
 _     _ _                         _
| |__ (_) |___      ____ _ _ __ __| | ___ _ __
| '_ \| | __\ \ /\ / / _` | '__/ _` |/ _ \ '_ \
| |_) | | |_ \ V  V / (_| | | | (_| |  __/ | | |
|_.__/|_|\__| \_/\_/ \__,_|_|  \__,_|\___|_| |_|

Open source password management solutions
Copyright 2015-2021, 8bit Solutions LLC
https://bitwarden.com, https://github.com/bitwarden

===================================================

/ownit/tmp/bitwarden-install.sh: 24: Bad substitution
bitwarden.sh version 1.41.3
Docker version 20.10.7, build f0df350
docker-compose version 1.29.2, build 5becea4c

/ownit/tmp/bitwarden-install.sh: 48: Syntax error: "(" unexpected
```

## Steps To Reproduce

1. `git clone https://github.com/MrHallway0/ownit.git`
2. `sh ./install.sh`

## Expected Result
Installation like normal. 

## Actual Result
Fails to install.

## Screenshots or Videos
![image](https://user-images.githubusercontent.com/65696362/123037541-ae293c00-d3a3-11eb-8dbb-49f32ccb457f.png)

## Environment
- Build Version: I honestly don't know (I am new to using Bitwarden). 
- Self Hosted: True
- Environment: Docker
- Hardware: 
![image](https://user-images.githubusercontent.com/65696362/123037778-1b3cd180-d3a4-11eb-99e4-5b0fef11dc02.png)

## Additional Context
I am installing using my script: https://github.com/MrHallway0/ownit.

**Comment by TypicalDarkness** [comment] 2021-06-28 14:11
I think the problem is that you are using sh

Try to use
```
./install.sh
```
or
```
bash install.sh
```
Yes, I know the ".sh" extension is confusing...

**Comment by MrHallway0** [comment] 2021-06-28 16:47
That got past the Bad substitution but now I get `mkdir: cannot create directory ‘/ownit/tmp/bwdata’: Permission denied` even though the `bitwarden` user is being used.

**Comment by eliykat** [comment] 2021-06-28 21:39
You created the `/ownit` directory using whatever user is running the script, then you `sudo -u bitwarden` to run the install script. My guess is that the `bitwarden` user does not have permissions for the `/ownit` directory. You'll need to `chmod` or `chown` etc.

We use GitHub issues as a place to track bugs and other development related issues. I thought the initial issue may have been a bug with our install script, but it looks like the issues you're experiencing are more to do with your custom install script. I suggest that you continue this discussion with other Bitwarden users on our [community forums](https://community.bitwarden.com/c/support/). As this is not a bug with Bitwarden, I'll close the issue here.

**Closed by eliykat** 2021-06-28 21:39 UTC
