### ISSUE TITLE
SMTP authentication not proceeding correctly

### ISSUE THREAD

**Issue by kc9jud** [bitwarden/server#361] opened 2018-09-26 03:22 UTC
Hi, it appears that Bitwarden is not correctly authenticating to my SMTP server. The output from Postfix when Bitwarden tries to send an email looks something like
```
Sep 26 03:11:00 mail postfix/submission/smtpd[23604]: connect from c-XXX-XXX-XXX-XXX.hsd1.in.comcast.net[XXX.XXX.XXX.XXX]
Sep 26 03:11:01 mail postfix/submission/smtpd[23604]: NOQUEUE: reject: RCPT from c-XXX-XXX-XXX-XXX.hsd1.in.comcast.net[XXX.XXX.XXX.XXX]: 554 5.7.1 <me@example.com>: Recipient address rejected: Access denied; from=<bitwarden@example.com> to=<me@example.com> proto=ESMTP helo=<bitwarden.example.com>
Sep 26 03:11:01 mail postfix/submission/smtpd[23604]: lost connection after RCPT from c-XXX-XXX-XXX-XXX.hsd1.in.comcast.net[XXX.XXX.XXX.XXX]
Sep 26 03:11:01 mail postfix/submission/smtpd[23604]: disconnect from c-XXX-XXX-XXX-XXX.hsd1.in.comcast.net[XXX.XXX.XXX.XXX] ehlo=2 starttls=1 mail=1 rcpt=0/1 commands=4/5
```
However, I can successfully send email with the same credentials and SSL settings from Thunderbird, with the Postfix log:
```
Sep 26 03:01:23 mail postfix/submission/smtpd[23449]: connect from c-XXX-XXX-XXX-XXX.hsd1.in.comcast.net[XXX.XXX.XXX.XXX]
Sep 26 03:01:40 mail postfix/submission/smtpd[23449]: 61063A35AD: client=c-XXX-XXX-XXX-XXX.hsd1.in.comcast.net[XXX.XXX.XXX.XXX], sasl_method=PLAIN, sasl_username=bitwarden
Sep 26 03:01:40 mail postfix/cleanup[23455]: 61063A35AD: message-id=<7c2b7014-e701-0795-803d-e5453176068f@example.com>
Sep 26 03:01:40 mail postfix/qmgr[1291]: 61063A35AD: from=<bitwarden@example.com>, size=788, nrcpt=1 (queue active)
Sep 26 03:01:40 mail postfix/submission/smtpd[23449]: disconnect from c-XXX-XXX-XXX-XXX.hsd1.in.comcast.net[XXX.XXX.XXX.XXX] ehlo=2 starttls=1 auth=1 mail=1 rcpt=1 data=1 quit=1 commands=8
```
Notice, the essential difference is the `sasl_method=PLAIN` and `sasl_username=bitwarden`, as well as the `auth=1` indicating that the connection was successfully authenticated. Is there some configuration flag I need to turn on to have Bitwarden attempt to login?

P.S. Obviously I have sanitized those log outputs a bit.

**Comment by kspearrin** [comment] 2018-09-26 04:04
Does the `authType` setting solve this? https://github.com/bitwarden/core/issues/355

**Comment by kc9jud** [comment] 2018-09-26 04:13
It doesn't appear to -- I've tried `authType=PLAIN` and `authType=LOGIN`, but no luck.

**Comment by kc9jud** [comment] 2018-09-26 06:36
My mail server is set up not to advertise authentication being available until after STARTTLS has succeeded (to prevent passwords accidentally being sent plaintext) — is it possible that the SMTP library decides whether to do authentication *before* acquiring a secure channel?

**Comment by kspearrin** [comment] 2018-09-26 11:57
It seems starttls is supported: https://docs.microsoft.com/en-us/dotnet/api/system.net.mail.smtpclient.enablessl?view=netframework-4.7.2#remarks

**Comment by kc9jud** [comment] 2018-09-28 00:49
Is there anything else I can do to try to debug this?

**Comment by Dennis14e** [comment] 2018-10-19 18:10
I might have the same issue.
As mail server I use [Mailu](https://github.com/Mailu/Mailu).

global.override.env:
```
globalSettings__mail__replyToEmail=noreply@MY_DOMAIN.TLD
globalSettings__mail__smtp__host=FQDN.MY_DOMAIN.TLD
globalSettings__mail__smtp__username=noreply@MY_DOMAIN.TLD
globalSettings__mail__smtp__password=MY_PASSWORD
globalSettings__mail__smtp__ssl=true
globalSettings__mail__smtp__port=587
globalSettings__mail__smtp__useDefaultCredentials=false
globalSettings__mail__smtp__authType=PLAIN
```

Bitwarden log:
```
2018-10-19 17:59:08.001 +00:00 [Error] Mail send failed.
System.Net.Mail.SmtpException: The SMTP server requires a secure connection or the client was not authenticated. The server response was: 5.7.1 Authentication required
   at System.Net.Mail.MailCommand.CheckResponse(SmtpStatusCode statusCode, String response)
   at System.Net.Mail.MailCommand.EndSend(IAsyncResult result)
   at System.Net.Mail.SendMailAsyncResult.SendMailFromCompleted(IAsyncResult result)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Mail.SendMailAsyncResult.End(IAsyncResult result)
   at System.Net.Mail.SmtpClient.SendMailCallback(IAsyncResult result)
```

Mailu log:
` 2018/10/19 18:05:57 [info] 9#9: *1007 client was rejected: "MAIL FROM:<noreply@MY_DOMAIN.TLD>__" while in auth state, client: MY_IP using starttls, server: 0.0.0.0:587`

**Comment by plwc** [comment] 2018-11-05 05:40
I have a similar setup and I'm also getting exactly the same errors in the logs. I've been back and forth for a day now trying different options and the best I've gotten is that when I use globalSettings_mail_smtp_authType=LOGIN I get somethingthat looks a bit closer to what I get on successful sends with systems other than Bitwarden.

With all other programs my server works fine with 465 or 587 and with SSL/TLS or STARTTLS.

**Comment by kspearrin** [comment] 2018-11-05 12:53
I am not sure what else to suggest at the moment. Here is the code that we use for sending SMTP mail from .NET Core:

https://github.com/bitwarden/core/blob/master/src/Core/Services/Implementations/SmtpMailDeliveryService.cs#L35

**Comment by plwc** [comment] 2018-11-06 02:31
Thanks, we'll have a look over that and see if we can figure it out.

FYI for anyone interested, these are the first few lines from our docker logs using Thunderbird with STARTTLS

**front_1_1b0c71b82edf | 2018/11/06 02:22:18 [info] 18#18: *27309 client 10.0.10.2:60115 connected to 0.0.0.0:587
front_1_1b0c71b82edf | 127.0.0.1 - - [06/Nov/2018:02:22:19 +0000] "GET /auth/email HTTP/1.0" 200 0 "-" "-"
admin_1_ab93d4744f7b | 172.18.0.3 - - [06/Nov/2018:02:22:19 +0000] "GET /internal/auth/email HTTP/1.0" 200 - "-" "-"**

And this is what it looks like when we use the same settings with BItWarden.

**front_1_1b0c71b82edf | 2018/11/06 02:19:26 [info] 18#18: *27308 client 10.0.10.2:44313 connected to 0.0.0.0:587
front_1_1b0c71b82edf | 2018/11/06 02:19:26 [info] 18#18: *27308 client was rejected: "MAIL FROM:<validemail@validcomain>__" while in auth state, client: 10.0.10.2 using starttls, server: 0.0.0.0:587**

**Comment by kspearrin** [comment] 2018-11-06 13:15
@plwc Please let us know if you figure anything out.

**Comment by syrm** [comment] 2018-12-06 08:40
Same problem with this setup : 
`globalSettings__mail__replyToEmail=xxxxx
globalSettings__mail__smtp__host=smtp.gmail.com
globalSettings__mail__smtp__username=xxxxx
globalSettings__mail__smtp__password=xxxxx
globalSettings__mail__smtp__ssl=true
globalSettings__mail__smtp__port=587
globalSettings__mail__smtp__useDefaultCredentials=false
`

**Comment by kspearrin** [comment] 2018-12-06 12:38
@syrm For gmail you have to enable "less secure apps" to use SMTP: https://support.google.com/accounts/answer/6010255?hl=en

**Comment by syrm** [comment] 2018-12-06 13:08
> @syrm For gmail you have to enable "less secure apps" to use SMTP: https://support.google.com/accounts/answer/6010255?hl=en

Perfect !

**Comment by kc9jud** [comment] 2019-01-24 07:59
BTW, according to the [.NET documentation](https://docs.microsoft.com/en-us/dotnet/api/system.net.mail.smtpclient?view=netframework-4.7.2), SmtpClient is obsolete and
> SmtpClient and its network of types are poorly designed, we strongly recommend you use https://github.com/jstedfast/MailKit and https://github.com/jstedfast/MimeKit instead

This might just be a bug in an unsupported library...

**Comment by alelapeyre** [comment] 2019-01-24 08:54
@kc9jud An upgrade to MailKit has been made by @kspearrin. See #431.

**Comment by kc9jud** [comment] 2019-01-24 14:32
@alelapeyre Great — I’ll check if this is fixed by the next release.

**Comment by cooperaj** [comment] 2019-02-20 16:19
Just hit this issue after switching to Mailu as a mail server. I'm currently unable to login to the admin area. 

My configuration matches @Dennis14e above.

**Comment by maaeps** [comment] 2019-04-20 11:59
@cooperaj My bitwarden can not send mails with mailu as well. Have you managed to solve the problem already?

**Comment by maaeps** [comment] 2019-04-20 12:52
My bitwarden works now with mailu.
My env variables:
```
globalSettings__mail__smtp__host=front.mailserver
globalSettings__mail__smtp__port=10025
globalSettings__mail__smtp__ssl=false
globalSettings__mail__smtp__startTls=false
globalSettings__mail__smtp__trustServer=true
```

front.mailserver solved to my front container from mailu.

**Comment by gr33k** [comment] 2020-01-13 03:09
globalSettings__mail__smtp__trustServer=true is what FINALLY fixed this!!!!!
Thank you @maaeps ! You answered it when Bitwarden themselves had no solutions for these.

Darn product is too sensitive with certs....biggest pain of all my services when I expected this to be one of the easiest.

**Comment by Dennis14e** [comment] 2020-03-15 18:42
The problem should be fixed just like #457 with the new update.

**Comment by brgirgis** [comment] 2021-02-03 04:56
I had to generate an "App password" from Google as per this answer https://support.google.com/accounts/answer/185833.
Here is my setup:
```
globalSettings__mail__replyToEmail=no-reply@example.com
globalSettings__mail__From=no-reply@example.com
globalSettings__mail__smtp__host=smtp.gmail.com
globalSettings__mail__smtp__port=587
globalSettings__mail__smtp__ssl=true
globalSettings__mail__smtp__username=myemail@gmail.com
globalSettings__mail__smtp__password=GOOGLE_APP_PASSWORD
```

**Comment by djsmith85** [comment] 2021-12-16 12:05
Closing this issue as it appears the originally posted problem has been resolved. If this happens again or continues to be an issue please feel free to re-open this issue and let us know, along with any additional detail to assist with reproduction and root cause analysis.

**Closed by djsmith85** 2021-12-16 12:05 UTC

**Comment by josedorado1** [comment] 2022-02-03 11:51
Hi all,

I'm new to this sort of thing and installed Bitwarden on Centos 7 and was looking to connect it to Postfix to forward the verification email but I have no idea where to start. A lot of resources online offer solutions for Ubuntu but very little for Centos 7. Any help would be amazing!

**Comment by eliykat** [comment] 2022-02-09 02:03
Hey @josedorado1, I recommend you create a thread in our [community forums](https://community.bitwarden.com/c/support/). You might get more engagement than on a closed issue.
