### ISSUE TITLE
certbot: error: unrecognized arguments: -encodedCommand MAA= xml -outputFormat text

### ISSUE THREAD

**Issue by lkloon123** [bitwarden/server#535] opened 2019-07-21 07:49 UTC
Hi, may i know why this certbot error occurs?
```bash
Status: Downloaded newer image for certbot/certbot:latest
usage:
  certbot [SUBCOMMAND] [options] [-d DOMAIN] [-d DOMAIN] ...

Certbot can obtain and install HTTPS/TLS/SSL certificates.  By default,
it will attempt to use a webserver both for obtaining and installing the
certificate.
certbot: error: unrecognized arguments: -encodedCommand MAA= xml -outputFormat text
```

**Comment by kspearrin** [comment] 2019-07-21 11:44
I have no idea, sorry. Never seen this error before.

**Comment by DonDino2** [comment] 2019-10-20 08:13
I am also seeing this error right now, during attempts to reinstall Bitwarden on my Win10 system.

**Comment by hiyan** [comment] 2019-11-15 19:42
I'm getting the same error. First try no such error. Then i screwed up and tried again (deleted bwdata folder) and now i'm getting the error.

Am on win10

**Comment by DonDino2** [comment] 2019-11-15 22:13
Unfortunately I never solved the mystery. I ended up reinstalling Windows but I now host Bitwarden on a linux server instead.

**Comment by lkloon123** [comment] 2019-11-20 03:40
@DonDino2 
yeah me too, seems like windows is producing the problem.

**Comment by hiyan** [comment] 2019-11-21 03:58
Update: Wasnt able to get it working.

Workaround: Since I had WSL running, I just ran certbot there and copied the files over manually. Working fine now.

**Comment by averkiev** [comment] 2020-01-08 14:13
Same error here on clean install of Windows 10 Pro 1909.

**Comment by alexwaibel** [comment] 2020-04-18 01:35
I am also having this issue on Windows 10 Pro 1903.

@hiyan could you elaborate on how you were able to run certbot on WSL? When I try this using `sudo certbot certonly --standalone` I get the error `The key authorization file from the server did not match`.

**Comment by hiyan** [comment] 2020-04-20 02:47
@alexwaibel I did not have this error. I believe yours may be a different error.

**Comment by chrizz1001** [comment] 2020-08-27 19:11
Same here. One day it stopped working. Also tried fresh install... nothin.

**Comment by chrizz1001** [comment] 2020-08-27 20:15
Yes, WSL (2) solution from  @hiyan works like charm!

- install WSL (2) [as described by docker ](https://docs.docker.com/docker-for-windows/wsl/)
- enter WSL container to bash (for me ubuntu)
- keep Docker for Windows running on host (its available in WSL)
- install bitwarden (I did it in ubuntu home dir "cd ~" in a subfolder "bitwarden") (if you purchased licenses also use you install id and key, you can find it in your old config override)
- if your old version broke you can [import your last DB backup](https://bitwarden.com/help/article/backup-on-premise/#restoring-a-nightly-backup)
- you can find you c hdd at /mnt/c/ to grab the backup file

hope there will be another solution anytime (soon) :D

**Comment by djsmith85** [comment] 2021-12-16 11:54
Closing this issue as it appears the originally posted problem has been resolved. If this happens again or continues to be an issue please feel free to re-open this issue and let us know, along with any additional detail to assist with reproduction and root cause analysis.

**Closed by djsmith85** 2021-12-16 11:54 UTC
