### ISSUE TITLE
Vault items not displaying

### ISSUE THREAD

**Issue by edwardreed81** [bitwarden/server#2545] opened 2023-01-06 14:05 UTC
### Steps To Reproduce

1. Deployed using PostgreSQL database
2. Imported my items from LastPass `.csv`
3. Created an organization (family license)
4. Moved many items into the organization vault (couldn't do them all at once, but that's a separate issue)
5. Added my wife and child to the organization and created appropriate collections

### Expected Result

See all items in the personal and organization vault.

### Actual Result

No items are visible and the organization is not present.

### Additional Context

There's an exception in api.log (attached) that seems to indicate some sort of invalid entry in the database, but I can't be sure. I don't know what happened that caused it to go from working to not.

### Githash Version

3997defe-dirty

### Environment Details

- Ubuntu Server 20.04.5 LTS
- Docker 20.10.21
- Intel Core i7-2600, 16 GB RAM
[api.log](https://github.com/bitwarden/server/files/10360626/api.log)

### Issue-Link

https://github.com/bitwarden/server/issues/2480

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by justindbaur** [comment] 2023-01-12 12:49
Possibly a duplicate of #2561 but I'm not quite confident in that enough to consolidate just yet.

**Comment by edwardreed81** [comment] 2023-01-12 14:12
I've since deployed the multi-container self hosting and it all seems to be working fine. So I don't think there's anything weird with my imported items that would screw things up.

**Comment by justindbaur** [comment] 2023-04-15 01:37
I'm still pretty sure this is a duplicate of #2561 and I have just made a PR to fix that one. Since you moved on to use the standard deployment I am going to close this issue in favor on tracking it all in that ticket.

**Closed by justindbaur** 2023-04-15 01:37 UTC
Labels: bug, bw-unified-deploy
