### ISSUE TITLE
BW 2024.4.2 update: The Compose file '/xxxxx/bwdata/docker/docker-compose.yml' is invalid because

### ISSUE THREAD

**Issue by spiezmaestro** [bitwarden/server#4068] opened 2024-05-08 07:55 UTC
### Steps To Reproduce

HI,

Just tried to update my selfhosted instance from 2024.4.1 to 2024.2. (./bitwarden.sh updateself && ./bitwarden.sh update) and get the below error message:

```
ERROR: The Compose file '/xxxxx/bwdata/docker/docker-compose.yml' is invalid because:
Unsupported config option for networks: 'default'
Unsupported config option for services: 'mssql'
```

Reverted to snapshot taken before the update, installed all outstanding Linux patches, rebooted, retried the update, same error.

Dit not change anything in the docker-compose.yml file.

### Expected Result

Clean update (as usual).

### Actual Result

```
5f678ea9f2e2: Pull complete 
ed17c50184b1: Pull complete 
857034bf1882: Pull complete 
84a7a4d4c8f6: Pull complete 
a8a07cfff5a2: Pull complete 
986f5e8a9717: Pull complete 
ea1134b602b2: Pull complete 
Digest: sha256:96f9299860ccc5ef9d16ccf59794a55a412cbaeacfbf09c188958e8d37764432
Status: Downloaded newer image for bitwarden/setup:2024.4.2
docker.io/bitwarden/setup:2024.4.2

Building docker environment files.
Building docker environment override files.
Building nginx config.
Building FIDO U2F app id.
Building docker-compose.yml.

ERROR: The Compose file '/xxxxx/bwdata/docker/docker-compose.yml' is invalid because:
Unsupported config option for networks: 'default'
Unsupported config option for services: 'mssql'
ERROR: The Compose file '/xxxxx/bwdata/docker/docker-compose.yml' is invalid because:
Unsupported config option for services: 'admin'
Unsupported config option for networks: 'default'
```

### Build Version

2024.4.1 wanted to upgrade to 2024.4.2

### Environment

Self-Hosted

### Environment Details

Ubuntu 22.04.4 completely patched with Bitwarden installed according to the selfhosting documentation on the help.bitwarden.com website.

### Issue Tracking Info

- [ ] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment] 2024-05-08 08:00
Duplicate of https://github.com/bitwarden/server/issues/4059

**Closed** 2024-05-08 08:00 UTC
Labels: bug
