### ISSUE TITLE
"Resource not found" trying to share a login to organization

### ISSUE THREAD

**Issue by ohthehugemanatee** [bitwarden/server#88] opened 2017-10-04 21:13 UTC
My family has one organization, with one shared collection. Tonight my wife created her account in response to my organization invitation. Once I had confirmed her on the organization, she could see the org and the collection. She tried to share a login to the collection by clicking "Share" from the item's gear menu in the web UI. The share form looked as expected; she checked the box for our collection and clicked the "Share" button.... and got a "Resource not found" error message.

I tried upgrading her from user to admin, no change. I wish I knew WHAT resource it couldn't find...

**Comment by kspearrin** [comment] 2017-10-04 21:15
Have her log out and back in. I think this is a known bug if that works.

**Comment by barnabynagy** [comment] 2019-05-05 07:18
I still have this issue. If this is a bug as you say it is why hasn't this been fixed yet since 2017? https://cl.ly/b503c4207f1b

**Comment by ldanicel** [comment] 2020-03-30 22:42
same use case... same issue.

**Comment by jobooker** [comment] 2021-02-08 13:58
Just encountered this as well. Free tier, added a second person, they ran into the above issue. I found this bug report and had them log out and log back in. That worked. Should this issue be reopened? Should I made a new one?

**Comment by jobooker** [comment] 2021-02-08 14:05
I just reproduced this with the same two users but going in the other direction. You must log out after accepting an invite (and perhaps it has to be after the inviter confirms you on their end?).

**Comment by 737simpilot** [comment] 2021-02-09 16:51
I can confirm this also happens at the Bitwarden site as well. Logging out solves the issue.

**Comment by mitchsw** [comment] 2021-02-17 03:01
I experienced this issue today. A logout resolved the problem, but this is clearly poor UX. Why is this bug closed?

**Comment by BNL-LeeWiscovitch** [comment] 2021-03-08 21:02
Confirming ran into this issue today. Logging out/in fixed it, but that isn't the best solution to this.

**Comment by jonleung** [comment] 2021-05-11 21:53
Happens for me as well: https://github.com/bitwarden/browser/issues/1534#issuecomment-839205452

**Comment by eliykat** [comment] 2021-05-12 00:28
I'm reopening this because it's still a bug, even if it's a known one. In my experience, the same thing happens when trying to save an item to a collection, if the user has not logged out and back in again since being confirmed to that org.

The problem appears to be that the server uses the `currentContext` object to track what org membership a user has, and this is not updated until the user logs out and back in.

**Comment by wearepariah** [comment] 2022-02-04 07:05
Still an issue today, when adding a user to an organisation it will give a "Resource not found" error until they log out and log back in. Any word on a fix?

**Comment by ifernandezdiaz** [comment] 2022-08-05 13:24
Hi, @wearepariah! I tried to replicate it with no luck. But I mark it as a bug in our internal tool to investigate it better and fix it as soon as we can.

**Comment by janrrrr** [comment] 2023-06-30 13:40
Still a thing. Invited a account to an organisation and the new account is not able to add a login to a collection of the orgranisation. LogOut and LogIn fixed it.

**Comment by fdfytr** [comment] 2023-09-14 14:12
6 years and same problem... wow
logout/login does not help...

**Comment by r-tome** [comment] 2024-04-19 09:31
We haven't been able to reproduce this on the latest version, so I'm closing it. I'm willing to reopen it if anyone is still experiencing this and can post the steps to reproduce it.

**Closed by r-tome** 2024-04-19 09:31 UTC
Labels: bug

**Comment by martinvw** [comment] 2025-04-22 19:28
Just bumped into this issue :( 

Signing out and in solved the issue...

**Comment by eliykat** [comment] 2025-07-19 03:42
Should be solved by #6097
