### ISSUE TITLE
Error: The Type Field is Required

### ISSUE THREAD

**Issue by notscottsmith** [bitwarden/server#1404] opened 2021-06-23 02:38 UTC
## Describe the Bug

Two users have gone through the account creation process via Single-Sign on and haven't received the verification emails, despite multiple attempts. When an admin goes into the interface for the organization to re-send the invitation, an error pops up saying: The Type Field is required.

## Steps To Reproduce

1. Go to organization
2. Manage
3. People
4. Click on cog next to user who's been invited, click Resend invitation
5. Error

## Expected Result

An email is sent to the user to get them verified

## Screenshots or Videos
In the logs:
https://pastebin.com/rtUQJuVi

![image](https://user-images.githubusercontent.com/51853082/123026555-f6ca0f00-d40e-11eb-998c-ffe12b8a91f1.png)
![image](https://user-images.githubusercontent.com/51853082/123026525-ee71d400-d40e-11eb-87de-a9287242bb39.png)

## Environment

Server Installed
    1.41.3 
Web Installed
    2.20.3

**Comment by sso-bitwarden** [comment] 2021-06-23 03:58
Please remove the users then re-invite them.

They must complete the whole onboarding flow before they could use SSO
1. Received the invitation, click, then log in/create user
2. Log in to the account using the master password.
3.  Admin confirmed the user
4. User could use SSO.

**Comment by sso-bitwarden** [comment] 2021-06-23 03:59
If you are still having issue, please contact our helpdesk via https://bitwarden.com/contact/

**Comment by notscottsmith** [comment] 2021-06-23 04:17
> 
> 
> Please remove the users then re-invite them.
> 
> They must complete the whole onboarding flow before they could use SSO
> 
>     1. Received the invitation, click, then log in/create user
> 
>     2. Log in to the account using the master password.
> 
>     3. Admin confirmed the user
> 
>     4. User could use SSO.

The issue is failing at step 1 of your flow. The email isn't going out.

Looking a bit deeper, it is potentially because Bitwarden is bringing across an AD object without checking to see if all the criteria are met with regards to user configuration. I'm hypothesising as I haven't fully tested that theory yet.

**Comment by notscottsmith** [comment] 2021-06-25 05:01
Some more information regarding this. It seems unrelated to email delivery as the error message still occurs to a user who has successfully received the invitation email (but has yet to "accept" it) and an admin attempts to re-send the invitation email from the UI.

It seems that the invitation/signon on process for SSO is making assumptions about what data is available in the SAML claim and not prompting the user to populate the extra data it requires (or assumes will be there) which then leads to these errors.

**Comment by eliykat** [comment] 2021-06-25 05:39
The logs show that the error is originating from `MailKitSmtpMailDeliveryService.SendEmailAsync`, so it's related to the outgoing email service on self-hosted instances. The error indicates that it's trying to parse an empty or null email address.

> It seems that the invitation/signon on process for SSO is making assumptions about what data is available in the SAML claim and not prompting the user to populate the extra data it requires (or assumes will be there) which then leads to these errors.

Maybe! Could you make sure that your users have email addresses configured in the IdP?

What IdP are you using?

**Comment by notscottsmith** [comment] 2021-06-25 07:16
> 
> 
> The logs show that the error is originating from `MailKitSmtpMailDeliveryService.SendEmailAsync`, so it's related to the outgoing email service on self-hosted instances. The error indicates that it's trying to parse an empty or null email address. I'm not sure why this behaviour would be inconsistent though.
> 
> > It seems that the invitation/signon on process for SSO is making assumptions about what data is available in the SAML claim and not prompting the user to populate the extra data it requires (or assumes will be there) which then leads to these errors.
> 
> Seems like a reasonable explanation. Could you make sure that your users have email addresses configured in the IdP? (I'm sure you already have, just checking.)
> 
> What IdP are you using?

Well, no, as explained, the error occurs/is logged regardless of whether the email can be delivered or not. The error is complaining about a null field not being populated:
``
Value cannot be null. (Parameter 'text')
System.ArgumentNullException: Value cannot be null. (Parameter 'text')
``

So, is the field used for storing the email via SSO different in the table to the one populated manually via a regular sign-up form? Or is it stored at all? Only pulling the data via active the SSO session for the user while they're logged in so it stays in sync with current data in the IdP source?

The user and the invitation into the organization is successfully created (email address is the username), thus the email address exists and is used as part of the creation process via SAML.

We're using Azure for the IdP.

**Comment by eliykat** [comment] 2021-06-30 06:11
I've been unable to reproduce this locally and couldn't identify any likely cause without further information.

While I want to help, I'm doubling up with our Customer Success team, and they have better resources and response times to help troubleshoot this with you. It could be a bug, a misconfiguration, or something else. Please continue with our Customer Success team via email. I'll close this in the meantime, but if it's reproducible as a bug, I'll reopen it for further action. Sorry for any confusion.

**Closed by eliykat** 2021-06-30 06:11 UTC
