### ISSUE TITLE
Safari: Access-Control-Allow-Origin cannot contain more than one origin.

### ISSUE THREAD

**Issue by Livonias** [bitwarden/server#1186] opened 2021-03-05 08:24 UTC
Getting the error 'Access-Control-Allow-Origin cannot contain more than one origin.' on Safari.

Extension is working perfectly in Brave browser, but Safari gives above error upon logging in. Self hosted environment.

Server version 1.19.0, Bitwarden Mac version tried both 1.24.5 (official version Mac App Store) and 1.24.6 downloaded from bitwarden website. Having this issue for over 2 weeks now.

**Comment by Livonias** [comment] 2021-03-10 07:53
Still having this issue, very annoying since Safari is my main browser.

**Comment by cscharf** [comment] 2021-03-10 15:11
Hi @Livonias , not sure why you're getting this error, I am unable to reproduce on our current test local instances. Do you have a modified nginx configuration file or docker-compose settings in your setup?

Also, the new Web Extension will be released here very shortly (< 1 week's time) that will replace the legacy App Extension for Safari when Bitwarden Desktop is installed from the Mac App Store. Hopefully that resolves the issue for you.

**Comment by clayadams5226** [comment] 2021-03-11 15:58
Hey @Livonias, Thank you for getting in touch and bringing this to our attention! We'd like to assist you further. We ask that you please contact us using our contact page, here: https://bitwarden.com/contact. You can include a link to this issue in the message content. The issue here will be closed and moved over to our Help Desk.

**Closed by clayadams5226** 2021-03-11 15:58 UTC
