### ISSUE TITLE
Release notes, Bug fixes... details please?

### ISSUE THREAD

**Issue by BloodyIron** [bitwarden/server#1920] opened 2022-03-17 04:47 UTC
Hey, for releases, can we please get actual details instead of just:

* Bug Fixes

Please? Like, I dunno, maybe link to the bugs that were fixed? The github issues, add some details, stuff like that.

It really makes my job as head of ITSec harder when I don't know _which release_ fixes _which bugs_. Cmonnnn ;) You know you should... ;)

The last 9x (or more?, in a row no less) releases have this problem.

**Comment by dwbit** [comment] 2022-03-17 19:31
Thanks for the feedback @BloodyIron, I'll pass it along to the team. Since this is not a bug, I'll close the issue now.

To continue the conversation, join us on the [Bitwarden Community Forums](https://community.bitwarden.com/) where you can discuss all things Bitwarden, including posting and voting for a feature request such as this one.

**Closed by dwbit** 2022-03-17 19:31 UTC
Labels: bug
