### ISSUE TITLE
Cannot add collections to accounts

### ISSUE THREAD

**Issue by joachimmathes** [bitwarden/server#2906] opened 2023-05-04 12:47 UTC
### Steps To Reproduce

1. Go to 'Organization Members'
2. Edit a member.
3. Go to tab 'Collections'
![screenshot_2023-05-04_13-02-14](https://user-images.githubusercontent.com/153653/236197043-a1ec9c9f-526a-486a-af07-d53b47f78f84.png)
5. Set 'Permission' and 'Select Collections'
6. Click on 'Save'

### Expected Result

Settings are stored properly without any error message.

### Actual Result

Popup with error message:
![screenshot_2023-05-04_11-34-58](https://user-images.githubusercontent.com/153653/236184394-3e4f1177-4cf8-482f-a105-1e7b8db99f9c.png)

### Additional Context

API log with
- Guids obfuscated in RequestPath
- Number of digits preserved in RequestPath
```
bitwarden-api    | fail: Bit.Api.Utilities.ExceptionHandlerFilterAttribute[0]
bitwarden-api    |       => SpanId:97a1ab0487a2d895, TraceId:ce080de2ff40a764a775324addecc849, ParentId:0000000000000000 => ConnectionId:0HMQ9IHIIRUJM => RequestPath:/organizations/11111111-1111-1111-1111-111111111111/users/22222222-2222-2222-2222-222222222222 RequestId:0HMQ9IHIIRUJM:00000002 => Bit.Api.Controllers.OrganizationUsersController.Put (Api)
bitwarden-api    |       Guid should contain 32 digits with 4 dashes (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx).
bitwarden-api    |       System.FormatException: Guid should contain 32 digits with 4 dashes (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx).
bitwarden-api    |          at System.Guid.GuidResult.SetFailure(Boolean overflow, String failureMessageID)
bitwarden-api    |          at System.Guid.TryParseExactD(ReadOnlySpan`1 guidString, GuidResult& result)
bitwarden-api    |          at System.Guid.TryParseGuid(ReadOnlySpan`1 guidString, GuidResult& result)
bitwarden-api    |          at System.Guid..ctor(String g)
bitwarden-api    |          at Bit.Api.Models.Request.SelectionReadOnlyRequestModel.ToSelectionReadOnly() in /home/runner/work/server/server/src/Api/Models/Request/SelectionReadOnlyRequestModel.cs:line 15
bitwarden-api    |          at Bit.Api.Controllers.OrganizationUsersController.<>c.<Put>b__21_0(SelectionReadOnlyRequestModel c) in /home/runner/work/server/server/src/Api/Controllers/OrganizationUsersController.cs:line 284
bitwarden-api    |          at System.Linq.Enumerable.SelectListIterator`2.MoveNext()
bitwarden-api    |          at Bit.Infrastructure.Dapper.DapperHelpers.ToArrayTVP(IEnumerable`1 values) in /home/runner/work/server/server/src/Infrastructure.Dapper/DapperHelpers.cs:line 46
bitwarden-api    |          at Bit.Infrastructure.Dapper.Repositories.OrganizationUserRepository.ReplaceAsync(OrganizationUser obj, IEnumerable`1 collections) in /home/runner/work/server/server/src/Infrastructure.Dapper/Repositories/OrganizationUserRepository.cs:line 326
bitwarden-api    |          at Bit.Core.Services.OrganizationService.SaveUserAsync(OrganizationUser user, Nullable`1 savingUserId, IEnumerable`1 collections, IEnumerable`1 groups) in /home/runner/work/server/server/src/Core/Services/Implementations/OrganizationService.cs:line 1552
bitwarden-api    |          at Bit.Api.Controllers.OrganizationUsersController.Put(String orgId, String id, OrganizationUserUpdateRequestModel model) in /home/runner/work/server/server/src/Api/Controllers/OrganizationUsersController.cs:line 283
bitwarden-api    |          at lambda_method346(Closure , Object )
bitwarden-api    |          at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
bitwarden-api    |          at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
bitwarden-api    |          at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
bitwarden-api    |          at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
bitwarden-api    |          at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
bitwarden-api    |          at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
bitwarden-api    |          at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|26_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
```

### Build Version

2023.4.2

### Environment

Self-Hosted

### Environment Details

- Operating System: CentOS Linux

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Neonwarden** [comment] 2023-05-04 20:10
Hi there!

Thank you for your report, it seems like it is a duplicate of this one [link to the original GitHub issue]. 

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This issue will now be closed.

Thanks!

Duplicate: https://github.com/bitwarden/clients/issues/5328

**Closed by Neonwarden** 2023-05-04 20:10 UTC
Labels: bug
