### ISSUE TITLE
Generating key for IdentityServer fails during install. Access to the path '/bitwarden/identity/' is denied.

### ISSUE THREAD

**Issue by Zadeis** [bitwarden/server#885] opened 2020-08-22 22:54 UTC
My intent is to setup a docker instance of bitwarden. While I have run the bitwarden.sh script once before successfully I wanted to change the directory where everything was being stored and decided to run the install again. Now when the process reaches the step of Generating key for IdentityServer it fails with a access denied exception. The output is below.

This is after providing the domain for the instance, saying no for generating a free lets encrypt SSL cert, the images are downloaded successfully, the installation id is provided, the installation key is provided, saying no to having an SSL cert and no for generating a self-signed cert.

```
Generating key for IdentityServer.
Unhandled exception. System.UnauthorizedAccessException: Access to the path '/bitwarden/identity/' is denied.
 ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at System.IO.FileSystem.CreateDirectory(String fullPath)
   at System.IO.Directory.CreateDirectory(String path)
   at Bit.Setup.CertBuilder.BuildForInstall() in /home/runner/work/server/server/util/Setup/CertBuilder.cs:line 72
   at Bit.Setup.Program.Install() in /home/runner/work/server/server/util/Setup/Program.cs:line 93
   at Bit.Setup.Program.Main(String[] args) in /home/runner/work/server/server/util/Setup/Program.cs:line 65
```

I see that it is concerned with the '/bitwarden/identity/' however I don't know what that location is in order to further diagnose the issue. It's probably something obvious that I'm not picking up on but any assistance would be appreciated. This is all being done on a synology NAS x86 based NAS if that makes any difference.

**Comment by kspearrin** [comment] 2020-08-24 14:05
@mportune-bw

**Comment by Zadeis** [comment] 2020-09-01 13:41
Is there additional information required for this? I'm happy to provide anything that would assist in figuring what I or whatever else is doing wrong.

**Comment by mportune-bw** [comment] 2020-09-01 14:13
Hi @Zadeis , was your previous (successful) installation performed on the same NAS?  If so, I'm curious about the directory structure I'm seeing in the error message since I'm unfamiliar with DSM having a `/home` folder outside of `/VolumeX`.  Did you install docker from the package center?  Can you describe your setup further?

**Comment by Zadeis** [comment] 2020-09-02 11:55
Yes the same previously successful install was on the same NAS. 

The location of my bwdata folder created by the script is in my "/volume1/Personal_Service_Data/bitwarden"

My "homes" directory is in the same volume1.

I have installed docker from the package center.

As far as I can tell there is nothing unique on my system that would affect this, specially seeing I have successfully set this once before as I stated, though our digging may further reveal something.

**Comment by Zadeis** [comment] 2020-09-12 16:48
Can I offer any other information to help or assist with diagnosing this problem?

**Comment by mportune-bw** [comment] 2020-09-14 17:07
@Zadeis Are you running the install command with su privileges?  Docker runs as root by default on DSM and the docker group isn't created by default.  (There appear to be some workarounds to create the group and force docker to respect it, but I wouldn't advise it)

**Comment by Zadeis** [comment] 2020-09-14 17:29
Correct I am running via the "sudo ./bitwarden.sh install" via ssh on my Synology system. I am also specifically using the admin account (which has privileges to use sudo to start with by default) when I see the above exception/error.

**Comment by KmdKeen** [comment] 2020-09-16 14:43
Same error for me! Unable to install on Synology what was working on the same model with same config some months before. 

Any idea?

**Comment by mportune-bw** [comment] 2020-09-16 20:53
Sorry for the delayed responses - still trying to reproduce this on DSM 6.2.3-25426 Update 2 and not having much luck.  What DSM version are you guys running?

**Comment by KmdKeen** [comment] 2020-09-16 21:00
We're on DSM 6.2.3-25426 without Update 2
Blank and fresh installed docker 
Running "sudo ./bitwarden.sh install" as admin on ssh.

**Comment by Zadeis** [comment] 2020-09-16 21:44
And in my case I only encountered that error after deleting the bwdata folder, moving the script to another directory and running the install again.

**Comment by KmdKeen** [comment] 2020-09-17 07:43
Found the reason: "wwner" needs to have "full permission" on the volume where the script is running. "bwdata" has UID/PID 65534 and is unable to change anything if the owner-permission is missing on the volume. Now it's working fine!

**Comment by Zadeis** [comment] 2020-09-17 13:26
By owner is that a user that is literally "owner" or the admin user? Or a user with admin rights?

**Comment by KmdKeen** [comment] 2020-09-17 13:28
No... have a look at the permissions of your volume. When there is no entry "owner" you need to add him with "full contoll"

**Comment by mportune-bw** [comment] 2020-09-17 13:36
@KmdKeen I'm guessing your bwdata path is outside of the default "docker" shared folder as well?  (which is already configured with owner > full control by default)

**Comment by Zadeis** [comment] 2020-09-17 13:40
Should this script be run from the docker shared folder? Reading the installation documentation leads me to believe that the script, and subsequently the bwdata folder, can reside anywhere of your choosing. Hence the installation documentation states, "Download the main Bitwarden script to your machine in the desired location."

I'm assuming this is a limitation of Docker on Synology systems that I wasn't completely aware of.

**Comment by mportune-bw** [comment] 2020-09-17 13:47
Yeah Synology has their own way of doing things.  While most of it can be tweaked there is always the chance it could become un-tweaked in a subsequent update, breaking whatever you were relying on to work.  For this reason I always create a `bitwarden` folder inside of their `docker` folder, and run the script from there (so in the end all data lives at `/volume1/docker/bitwarden/bwdata`

**Comment by Zadeis** [comment] 2020-09-17 14:10
I'm not sure if that's a limitation of Docker on a Synology system though. I have successfully setup two other docker containers to use a location other than the default `docker` shared folder, which is not to be confused with a volume. 

I have successfully ran the script in the default `docker` shared folder. This isn't my preference as I have a single shared folder that is backed up to the cloud weekly in order to protect the data on that volume. 

I will look into the permissions of the docker folder further but I find it odd I have sucessully setup two other containers, even the bitwarden one once but subsequent runs were unsuccessful, but this bitwarden instance seems to be giving me trouble.

I have also deleted the bwdata after a successful install and ran the install again to see if I received the same error and I did not so the issue seems to be limited to how permissions are handled by Synology DSM and the Docker software on Synology systems.

**Comment by mportune-bw** [comment] 2020-09-17 14:19
I'd say it's more of an implementation than a limitation :)  Regardless, thanks to @KmdKeen it sounds like this simply came down to permissions.  I'm not sure why it only started giving you trouble recently though, that's something I'll keep an eye on.  Closing this for now - feel free to re-open if needed.

**Closed by mportune-bw** 2020-09-17 14:19 UTC

**Comment by KmdKeen** [comment] 2020-09-17 16:16
> @KmdKeen I'm guessing your bwdata path is outside of the default "docker" shared folder as well? (which is already configured with owner > full control by default)

You're correct. I did make a new volume for docker-shares.
