### ISSUE TITLE
mssql failure with Kernel 6.7.X

### ISSUE THREAD

**Issue by ahrtmn** [bitwarden/server#3737] opened 2024-02-04 21:43 UTC
### Steps To Reproduce

1. Update host system to Linux 6.7.X kernel.
2. Run 2024.1.+ and observe mssql container failure

### Expected Result

All service containers healthy.

### Actual Result

```
This program has encountered a fatal error and cannot continue running at Sun Feb  4 19:40:41 2024
The following diagnostic information is available:

         Reason: 0x00000001
         Signal: SIGABRT - Aborted (6)
          Stack:
                 IP               Function
                 ---------------- --------------------------------------
                 000058b8ddf58a9c <unknown>
                 000058b8ddf584e2 <unknown>
                 000058b8ddf57af1 <unknown>
                 00007865dadcc090 killpg+0x40
                 00007865dadcc00b gsignal+0xcb
                 00007865dadab859 abort+0x12b
                 000058b8ddecf692 <unknown>
                 000058b8ddf6bc44 <unknown>
                 000058b8ddf9e248 <unknown>
                 000058b8ddf9e02a <unknown>
                 000058b8ddedb50a <unknown>
                 000058b8ddedb15f <unknown>
        Process: 47 - sqlservr
         Thread: 123 (application thread 0x144)
    Instance Id: a755eead-0955-43c9-895a-51fb785e5df3
       Crash Id: 45b9c5c9-83eb-4d73-8b77-6d4ca2349c48
    Build stamp: e5dea205d0938e2848fb2509856a7e8f30783e6d5f62d0c88355e288de0db89a
   Distribution: Ubuntu 20.04.4 LTS
     Processors: 4
   Total Memory: 4106240000 bytes
      Timestamp: Sun Feb  4 19:40:41 2024
     Last errno: 2
Last errno text: No such file or directory
Capturing a dump of 47
Successfully captured dump: /var/opt/mssql/log/core.sqlservr.2_4_2024_19_40_41.47
Executing: /opt/mssql/bin/handle-crash.sh with parameters
     handle-crash.sh
     /opt/mssql/bin/sqlservr
     47
     /opt/mssql/bin
     /var/opt/mssql/log/

     a755eead-0955-43c9-895a-51fb785e5df3
     45b9c5c9-83eb-4d73-8b77-6d4ca2349c48

     /var/opt/mssql/log/core.sqlservr.2_4_2024_19_40_41.47

Ubuntu 20.04.4 LTS
Capturing core dump and information to /var/opt/mssql/log...
/bin/cat: /proc/47/maps: Permission denied
```

### Additional Context

All containers 'healthy' with Kernel 6.6.10.

### Build Version

2024.1.+

### Environment

Self-Hosted

### Environment Details

- Arch Linux 
   - Kernels 6.7.3-arch1-1, 6.7.3-arch1-2
- Docker version 24.0.7, build afdd53b4e3
- Docker Compose version 2.23.3

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Greenderella** [comment] 2024-02-05 08:50
Hi there!

Thank you for your report, it seems like it is a duplicate of this one microsoft/mssql-docker#868

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there.

This issue will now be closed.

Thanks!

**Closed by Greenderella** 2024-02-05 08:50 UTC
Labels: bug
