### ISSUE TITLE
Can't connect bitwarden to external MSSQL Server

### ISSUE THREAD

**Issue by Miglanc7824** [bitwarden/server#1028] opened 2020-12-05 16:39 UTC
Hello,
I was able to successfully install the bitwarden server in self-hosted mode. Bitwarden is installed in the Docker environment. Everything works correctly. I wanted to test the option of connecting the server to an external MSSQL database server. I made an appropriate entry in the /bwdata/env/global.override.env file. After saving the changes, I ran the command ./bitwarden updatedb.

The system returned the following error:
`user00@user00:~$ ./bitwarden.sh updatedb
 _     _ _                         _
| |__ (_) |___      ____ _ _ __ __| | ___ _ __
| '_ \| | __\ \ /\ / / _` | '__/ _` |/ _ \ '_ \
| |_) | | |_ \ V  V / (_| | | | (_| |  __/ | | |
|_.__/|_|\__| \_/\_/ \__,_|_|  \__,_|\___|_| |_|

Open source password management solutions
Copyright 2015-2020, 8bit Solutions LLC
https://bitwarden.com, https://github.com/bitwarden

===================================================

Docker version 19.03.13, build 4484c46d9d
docker-compose version 1.27.4, build 40524192

1.38.1: Pulling from bitwarden/setup
Digest: sha256:5d1747477a30b7f466253a87f1232eb95bba9fe18ea613677b53206f63a53e48
Status: Image is up to date for bitwarden/setup:1.38.1
docker.io/bitwarden/setup:1.38.1
docker: Error response from daemon: Invalid network mode: invalid container format container:<name|id>.
See 'docker run --help'.`

Can you show me where I made a mistake? What else can I do?

I have the same problem when I try to connect to the MSSQL server (VM VMware) and MSSQL Docker container.

**Comment by SergeantConfused** [comment] 2020-12-05 16:59
Hi there,

I recommend checking out the following thread for more information on this: https://github.com/bitwarden/server/issues/473
I hope this helps, please keep me posted on this.


All the best,

**Comment by clayadams5226** [comment] 2021-01-08 05:39
Hi @Miglanc7824 , it looks like there is a viable workaround or resolution for the issue you're experiencing. Please let us know if this resolves the originally posted issue.

**Comment by clayadams5226** [comment] 2021-01-20 05:44
It appears we've not heard from you about this issue in some time. While we are now closing this issue, if it continues to be a problem please feel free to re-open this issue and provide any further information that may be helpful in reproducing the problem or helping you further.

**Closed by clayadams5226** 2021-01-20 05:44 UTC

**Comment by uhrm** [comment] 2023-03-02 12:57
Hi @clayadams5226, I'm experiencing the same issue (DB migrations don't work using an external MSSQL database). In your comment from Jan 8, 2021 you mentioned a viable workaround. Could you elaborate what that workaround is?

**Comment by clayadams5226** [comment] 2023-03-02 14:28
Hey @uhrm, there was a conversation around this in a different thread, https://github.com/bitwarden/server/issues/473 that was able to resolve the original poster's issue. Hopefully, you find it useful as well. If not, please feel free to reach out to our support team, https://bitwarden.com/contact/ for further troubleshooting tips
