### ISSUE TITLE
Bitwarden-nginx keeps restarting - wild card certificate

### ISSUE THREAD

**Issue by sinqbad** [bitwarden/server#577] opened 2019-10-12 11:04 UTC
I’m trying to get bitwarden to work on a wildcard certificate since I want to use other subdomains. I’m so close. Running docker ps shows that bitwarden-nginx keeps restarting.

    CONTAINER ID IMAGE COMMAND CREATED STATUS PORTS NAMES
    a4e238f5606c bitwarden/nginx:1.32.0 “/entrypoint.sh” 35 hours ago Restarting (1) 13 seconds ago bitwarden-nginx

I also changed the ports in an attempt to reverse proxy. Really new to all this. Should I be posting my config file online?

EDIT is my config file.

```
ssl_versions: 
# 
# SSL ciphersuites used by Nginx (ssl_ciphers). Leave empty for recommended default.
# Learn more: https://wiki.mozilla.org/Security/Server_Side_TLS
ssl_ciphersuites: 
# 
# Installation uses a managed Let's Encrypt certificate.
ssl_managed_lets_encrypt: false
# 
# The actual certificate. (Required if using SSL without managed Let's Encrypt)
# Note: Path uses the container's ssl directory. The `./ssl` host directory is mapped to
# `/etc/ssl` within the container.
ssl_certificate_path: ./ssl/bitwarden.example.com/fullchain.pem
# 
# The certificate's private key. (Required if using SSL without managed Let's Encrypt)
# Note: Path uses the container's ssl directory. The `./ssl` host directory is mapped to
# `/etc/ssl` within the container.
ssl_key_path: ./ssl/bitwarden.example.com/privkey.pem
# 
# If the certificate is trusted by a CA, you should provide the CA's certificate.
# Note: Path uses the container's ssl directory. The `./ssl` host directory is mapped to
# `/etc/ssl` within the container.
ssl_ca_path: ./ssl/bitwarden.example.com/fullchain.pem
# 
# Diffie Hellman ephemeral parameters
# Learn more: https://security.stackexchange.com/q/94390/79072
# Note: Path uses the container's ssl directory. The `./ssl` host directory is mapped to
# `/etc/ssl` within the container.
ssl_diffie_hellman_path: 
# 
# Communicate with the Bitwarden push relay service (push.bitwarden.com) for mobile
# app live sync.
push_notifications: true
# 
# Use a docker volume (`mssql_data`) instead of a host-mapped volume for the persisted database.
# WARNING: Changing this value will cause you to lose access to the existing persisted database.
# Learn more: https://docs.docker.com/storage/volumes/
database_docker_volume: false
# 
# Defines "real" IPs in nginx.conf. Useful for defining proxy servers that forward the 
# client IP address.
# Learn more: https://nginx.org/en/docs/http/ngx_http_realip_module.html
real_ips:
```

Please help, I can’t even figure out how to debug the issue.

**Comment by kspearrin** [comment] 2019-10-12 15:05
What logs are coming from the nginx container? Looking at your config, I will assume your ssl config path is not correct. Usually that starts with `/etc/ssl/...`

**Comment by m4gn3to** [comment] 2019-10-17 10:47
I'm also afected, but don't know how to debug, I've tried to connect to the container, but I can't as it is always restarting... How can I see the log?

**Comment by sinqbad** [comment] 2019-10-21 04:13
> What logs are coming from the nginx container? Looking at your config, I will assume your ssl config path is not correct. Usually that starts with `/etc/ssl/...`

How do I get the logs from the nginx container? I tried googling "nginx container docker" but couldn't find anything. New to all this, sorry.

**Comment by m4gn3to** [comment] 2019-10-21 07:31
You have to look inside the bwdata directory for the logs files, you will see the nginx directory with the nginx logs files.

**Comment by eric-gunn** [comment] 2020-02-11 14:46
@kspearrin I have the same issue:

Cert Location:
```
ls /etc/ssl/*.pem
/etc/ssl/intermediate.pem  /etc/ssl/internet-wildcard-key.pem  /etc/ssl/internet-wildcard.pem
```
Logs:
```
2020/02/11 14:29:52 [emerg] 1#1: cannot load certificate "/home/range/internet-wildcard.pem": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/home/range/internet-wildcard.pem','r') error:2006D080:BIO routines:BIO_new_file:no such file)
2020/02/11 14:29:54 [emerg] 1#1: cannot load certificate "/home/range/internet-wildcard.pem": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/home/range/internet-wildcard.pem','r') error:2006D080:BIO routines:BIO_new_file:no such file)
2020/02/11 14:29:56 [emerg] 1#1: cannot load certificate "/home/range/internet-wildcard.pem": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/home/range/internet-wildcard.pem','r') error:2006D080:BIO routines:BIO_new_file:no such file)
2020/02/11 14:29:58 [emerg] 1#1: cannot load certificate "/home/range/internet-wildcard.pem": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/home/range/internet-wildcard.pem','r') error:2006D080:BIO routines:BIO_new_file:no such file)
2020/02/11 14:30:00 [emerg] 1#1: cannot load certificate "/home/range/internet-wildcard.pem": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/home/range/internet-wildcard.pem','r') error:2006D080:BIO routines:BIO_new_file:no such file)
2020/02/11 14:30:02 [emerg] 1#1: cannot load certificate "/home/range/internet-wildcard.pem": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/home/range/internet-wildcard.pem','r') error:2006D080:BIO routines:BIO_new_file:no such file)
2020/02/11 14:30:07 [emerg] 1#1: cannot load certificate "/home/range/internet-wildcard.pem": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/home/range/internet-wildcard.pem','r') error:2006D080:BIO routines:BIO_new_file:no such file)
2020/02/11 14:30:14 [emerg] 1#1: cannot load certificate "/home/range/internet-wildcard.pem": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/home/range/internet-wildcard.pem','r') error:2006D080:BIO routines:BIO_new_file:no such file)
2020/02/11 14:30:28 [emerg] 1#1: cannot load certificate "/home/range/internet-wildcard.pem": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/home/range/internet-wildcard.pem','r') error:2006D080:BIO routines:BIO_new_file:no such file)
2020/02/11 14:30:55 [emerg] 1#1: cannot load certificate "/home/range/internet-wildcard.pem": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/home/range/internet-wildcard.pem','r') error:2006D080:BIO routines:BIO_new_file:no such file)
2020/02/11 14:31:47 [emerg] 1#1: cannot load certificate "/home/range/internet-wildcard.pem": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/home/range/internet-wildcard.pem','r') error:2006D080:BIO routines:BIO_new_file:no such file)
2020/02/11 14:32:48 [emerg] 1#1: cannot load certificate "/home/range/internet-wildcard.pem": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/home/range/internet-wildcard.pem','r') error:2006D080:BIO routines:BIO_new_file:no such file)
2020/02/11 14:33:49 [emerg] 1#1: cannot load certificate "/home/range/internet-wildcard.pem": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/home/range/internet-wildcard.pem','r') error:2006D080:BIO routines:BIO_new_file:no such file)
2020/02/11 14:34:50 [emerg] 1#1: cannot load certificate "/home/range/internet-wildcard.pem": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/home/range/internet-wildcard.pem','r') error:2006D080:BIO routines:BIO_new_file:no such file)
2020/02/11 14:35:52 [emerg] 1#1: cannot load certificate "/home/range/internet-wildcard.pem": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/home/range/internet-wildcard.pem','r') error:2006D080:BIO routines:BIO_new_file:no such file)
2020/02/11 14:36:53 [emerg] 1#1: cannot load certificate "/home/range/internet-wildcard.pem": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/home/range/internet-wildcard.pem','r') error:2006D080:BIO routines:BIO_new_file:no such file)
2020/02/11 14:37:25 [emerg] 1#1: cannot load certificate "/home/range/internet-wildcard.pem": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/home/range/internet-wildcard.pem','r') error:2006D080:BIO routines:BIO_new_file:no such file)
2020/02/11 14:37:27 [emerg] 1#1: cannot load certificate "/home/range/internet-wildcard.pem": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/home/range/internet-wildcard.pem','r') error:2006D080:BIO routines:BIO_new_file:no such file)
2020/02/11 14:37:29 [emerg] 1#1: cannot load certificate "/home/range/internet-wildcard.pem": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/home/range/internet-wildcard.pem','r') error:2006D080:BIO routines:BIO_new_file:no such file)
2020/02/11 14:37:30 [emerg] 1#1: cannot load certificate "/home/range/internet-wildcard.pem": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/home/range/internet-wildcard.pem','r') error:2006D080:BIO routines:BIO_new_file:no such file)
2020/02/11 14:37:32 [emerg] 1#1: cannot load certificate "/home/range/internet-wildcard.pem": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/home/range/internet-wildcard.pem','r') error:2006D080:BIO routines:BIO_new_file:no such file)
2020/02/11 14:37:35 [emerg] 1#1: cannot load certificate "/home/range/internet-wildcard.pem": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/home/range/internet-wildcard.pem','r') error:2006D080:BIO routines:BIO_new_file:no such file)
2020/02/11 14:37:39 [emerg] 1#1: cannot load certificate "/home/range/internet-wildcard.pem": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/home/range/internet-wildcard.pem','r') error:2006D080:BIO routines:BIO_new_file:no such file)
2020/02/11 14:37:47 [emerg] 1#1: cannot load certificate "/home/range/internet-wildcard.pem": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/home/range/internet-wildcard.pem','r') error:2006D080:BIO routines:BIO_new_file:no such file)
2020/02/11 14:38:01 [emerg] 1#1: cannot load certificate "/home/range/internet-wildcard.pem": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/home/range/internet-wildcard.pem','r') error:2006D080:BIO routines:BIO_new_file:no such file)
2020/02/11 14:38:27 [emerg] 1#1: cannot load certificate "/home/range/internet-wildcard.pem": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/home/range/internet-wildcard.pem','r') error:2006D080:BIO routines:BIO_new_file:no such file)
2020/02/11 14:39:20 [emerg] 1#1: cannot load certificate "/home/range/internet-wildcard.pem": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/home/range/internet-wildcard.pem','r') error:2006D080:BIO routines:BIO_new_file:no such file)
2020/02/11 14:40:21 [emerg] 1#1: cannot load certificate "/home/range/internet-wildcard.pem": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/home/range/internet-wildcard.pem','r') error:2006D080:BIO routines:BIO_new_file:no such file)
2020/02/11 14:41:25 [emerg] 1#1: cannot load certificate "/etc/ssl/internet-wildcard.pem": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/ssl/internet-wildcard.pem','r') error:2006D080:BIO routines:BIO_new_file:no such file)
2020/02/11 14:41:27 [emerg] 1#1: cannot load certificate "/etc/ssl/internet-wildcard.pem": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/ssl/internet-wildcard.pem','r') error:2006D080:BIO routines:BIO_new_file:no such file)
2020/02/11 14:41:29 [emerg] 1#1: cannot load certificate "/etc/ssl/internet-wildcard.pem": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/ssl/internet-wildcard.pem','r') error:2006D080:BIO routines:BIO_new_file:no such file)
2020/02/11 14:41:31 [emerg] 1#1: cannot load certificate "/etc/ssl/internet-wildcard.pem": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/ssl/internet-wildcard.pem','r') error:2006D080:BIO routines:BIO_new_file:no such file)
2020/02/11 14:41:33 [emerg] 1#1: cannot load certificate "/etc/ssl/internet-wildcard.pem": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/ssl/internet-wildcard.pem','r') error:2006D080:BIO routines:BIO_new_file:no such file)
2020/02/11 14:41:36 [emerg] 1#1: cannot load certificate "/etc/ssl/internet-wildcard.pem": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/ssl/internet-wildcard.pem','r') error:2006D080:BIO routines:BIO_new_file:no such file)
2020/02/11 14:41:40 [emerg] 1#1: cannot load certificate "/etc/ssl/internet-wildcard.pem": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/ssl/internet-wildcard.pem','r') error:2006D080:BIO routines:BIO_new_file:no such file)
2020/02/11 14:41:47 [emerg] 1#1: cannot load certificate "/etc/ssl/internet-wildcard.pem": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/ssl/internet-wildcard.pem','r') error:2006D080:BIO routines:BIO_new_file:no such file)
2020/02/11 14:42:01 [emerg] 1#1: cannot load certificate "/etc/ssl/internet-wildcard.pem": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/ssl/internet-wildcard.pem','r') error:2006D080:BIO routines:BIO_new_file:no such file)
2020/02/11 14:42:28 [emerg] 1#1: cannot load certificate "/etc/ssl/internet-wildcard.pem": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/ssl/internet-wildcard.pem','r') error:2006D080:BIO routines:BIO_new_file:no such file)
2020/02/11 14:43:20 [emerg] 1#1: cannot load certificate "/etc/ssl/internet-wildcard.pem": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/ssl/internet-wildcard.pem','r') error:2006D080:BIO routines:BIO_new_file:no such file)
```

**Comment by chefino** [comment] 2020-03-28 14:43
> @kspearrin I have the same issue:
> 
> Cert Location:
> 
> ```
> ls /etc/ssl/*.pem
> /etc/ssl/intermediate.pem  /etc/ssl/internet-wildcard-key.pem  /etc/ssl/internet-wildcard.pem
> ```
> 
> Logs:
> 
> ```
> 2020/02/11 14:41:25 [emerg] 1#1: cannot load certificate "/etc/ssl/internet-wildcard.pem": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/ssl/internet-wildcard.pem','r') error:2006D080:BIO routines:BIO_new_file:no such file)
> 2020/02/11 14:41:27 [emerg] 1#1: cannot load certificate "/etc/ssl/internet-wildcard.pem": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/ssl/internet-wildcard.pem','r') error:2006D080:BIO routines:BIO_new_file:no such file)
> 2020/02/11 14:41:29 [emerg] 1#1: cannot load certificate "/etc/ssl/internet-wildcard.pem": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/ssl/internet-wildcard.pem','r') error:2006D080:BIO routines:BIO_new_file:no such file)
> 2020/02/11 14:41:31 [emerg] 1#1: cannot load certificate "/etc/ssl/internet-wildcard.pem": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/ssl/internet-wildcard.pem','r') error:2006D080:BIO routines:BIO_new_file:no such file)
> 2020/02/11 14:41:33 [emerg] 1#1: cannot load certificate "/etc/ssl/internet-wildcard.pem": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/ssl/internet-wildcard.pem','r') error:2006D080:BIO routines:BIO_new_file:no such file)
> 2020/02/11 14:41:36 [emerg] 1#1: cannot load certificate "/etc/ssl/internet-wildcard.pem": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/ssl/internet-wildcard.pem','r') error:2006D080:BIO routines:BIO_new_file:no such file)
> 2020/02/11 14:41:40 [emerg] 1#1: cannot load certificate "/etc/ssl/internet-wildcard.pem": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/ssl/internet-wildcard.pem','r') error:2006D080:BIO routines:BIO_new_file:no such file)
> 2020/02/11 14:41:47 [emerg] 1#1: cannot load certificate "/etc/ssl/internet-wildcard.pem": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/ssl/internet-wildcard.pem','r') error:2006D080:BIO routines:BIO_new_file:no such file)
> 2020/02/11 14:42:01 [emerg] 1#1: cannot load certificate "/etc/ssl/internet-wildcard.pem": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/ssl/internet-wildcard.pem','r') error:2006D080:BIO routines:BIO_new_file:no such file)
> 2020/02/11 14:42:28 [emerg] 1#1: cannot load certificate "/etc/ssl/internet-wildcard.pem": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/ssl/internet-wildcard.pem','r') error:2006D080:BIO routines:BIO_new_file:no such file)
> 2020/02/11 14:43:20 [emerg] 1#1: cannot load certificate "/etc/ssl/internet-wildcard.pem": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/ssl/internet-wildcard.pem','r') error:2006D080:BIO routines:BIO_new_file:no such file)
> ```

You are probably storing your certificate files on the host system at `/etc/ssl`. You need to put them inside the `$PWD/bwdata/ssl` path.

Reading the config.yml, you can see:

> Note: Path uses the container's ssl directory. The `./ssl` host directory is mapped to
> # `/etc/ssl` within the container.

**Comment by paradoxicalNL** [comment] 2020-04-05 20:58
I struggled as well, I think especially users like me who normally configure nginx manually will have issues. But like as @chefino mentions:

_Note: Path uses the container's ssl directory. The ./ssl host directory is mapped to /etc/ssl within the container._

It's real simple, for future reference:

Your container root folder: bwdata
./ssl means the ssl folder in your root folder => /mylocation/bwdata/ssl
check your bwdata/config.yml:

_/etc/ssl/example.com/certificate.crt
/etc/ssl/example.com/private.key
/etc/ssl/example.com/ca.crt_

**If needed, update:**
bitwarden.sh stop
bitwarden.sh updateconfig

Your certificates go into => bwdata/ssl/example.com/certificate.crt ect ect

Now start! If you have issues, check rights on your files and/or logs.
These logs can be found in: /bwdata/logs/nginx

**Comment by timvahlbrock** [comment] 2021-08-01 20:13
Okay, so I just struggled for like 2 hours on this, the problem was, that I certbot generates the certificates into the `archive` directory and just uses symlinks to the newest one in the `live` directory. However, **docker compose does not support symlinks** which results in the _file not found_ error message. I am still trying to figure out how to still benefit from certbot's automatic renewable, as this isn't given when referencing the files in the archive directory.

**Comment by Hinton** [comment] 2021-12-14 12:40
I suspect the issue has been resolved. Docker compose mounts the directory which results in the symlink itself being mounted, not the destination. Maybe having a script that regularly checks if the cert has changed and copies to a local path would work @timvahlbrock.

I'm going to close this but feel free to re-open if the issue persists.

**Closed by Hinton** 2021-12-14 12:40 UTC

**Comment by timvahlbrock** [comment] 2021-12-14 12:44
I'm not sure how, but I did manage to achieve this without a script. But the installation I used no longer uses let's encrypt certificates, so I'm not able to check.

**Comment by tonyqus** [comment] 2022-02-07 19:44
I can reproduce the issue on windows.
![image](https://user-images.githubusercontent.com/772561/152859987-4dc159bb-000f-4a27-999d-71d593cf82be.png)

The folder of bwdata/ssl/localhost is empty. This means the certificate generation doesn't work during the installation.
