### ISSUE TITLE
Import from Lastpass (direct) did not import any URIs

### ISSUE THREAD

**Issue by mcdonamw** [bitwarden/server#4856] opened 2024-10-04 19:38 UTC
### Steps To Reproduce

1. Click extension icon
2. Click settings
3. Click Vault
4. Click Import Items
5. File format:  LastPass
6. Import directly from lastpass following necessary steps

### Expected Result

Lastpass vault imported correctly.

### Actual Result

None of the URIs for my Lastpass vault imported correctly.  All the URIs are various symbols, mostly square boxes, such as, �		

### Build Version

Version: 2024.10.0

### Environment

Cloud (bitwarden.com)

### Environment Details

OS: Windows 11 23H2
Browser: Chrome v129.0.6668.90 (Official Build) (64-bit)

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by jtodddd** [comment] 2024-10-04 20:37
Hi there!

Thank you for your report, it seems like it is a duplicate of this one https://github.com/bitwarden/clients/issues/11051  

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This issue will now be closed.

Thanks!

**Closed by jtodddd** 2024-10-04 20:37 UTC
Labels: bug
