### ISSUE TITLE
[Linux_Ubuntu20.04] Cannot create new entry

### ISSUE THREAD

**Issue by BestVanRome** [bitwarden/server#3988] opened 2024-04-15 11:49 UTC
### Steps To Reproduce

1. Go to 'add item'
2. Enter 'Name, Username and Password'
3. Click on ' Save'

### Expected Result

Creating new entry and giving a response that entry has been completed successfully-

### Actual Result

Error in ther upper right corner: 
Failed to decode acces token: JWT must have 3 parts

### Screenshots or Videos

![image](https://github.com/bitwarden/server/assets/62643607/c27b2990-c8d9-4c92-99e7-4e1e5f57b672)

### Additional Context

Version(installed and updated over Snap): 2024.4.0
Version 2024.4.0
Shell 28.2.8
Renderer 120.0.6099.291
Node 18.18.2
Architecture x64

### Githash Version

Installed over Snap, not sure if this fits in here :-/

### Environment Details

Version(installed and updated over Snap): 2024.4.0
Version 2024.4.0
Shell 28.2.8
Renderer 120.0.6099.291
Node 18.18.2
Architecture x64

### Issue-Link

https://github.com/bitwarden/server/issues/2480

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment] 2024-04-15 11:51
Duplicate of https://github.com/bitwarden/clients/issues/8722

**Comment by djsmith85** [comment] 2024-04-15 11:54
Hi there!

Thank you for your report, it seems like it is a duplicate of this one https://github.com/bitwarden/clients/issues/8722.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This issue will now be closed.

Thanks!

**Closed by djsmith85** 2024-04-15 11:54 UTC
Labels: bug, bw-unified-deploy
