### ISSUE TITLE
sync failure

### ISSUE THREAD

**Issue by michaelchettleburgh** [bitwarden/server#2581] opened 2023-01-13 20:26 UTC
### Steps To Reproduce

on iOS app (2023.1.0 (2886))
1. Go to Settings
2. Click on Sync
3. Click on "Sync vault now"

### Expected Result

successful syncing of ios data with on-prem vault

### Actual Result

ios error of "Syncing failed"

error from container : /etc/bitwarden/logs/api.log as below:

2023-01-13 20:17:09.328 +00:00 [ERR] An exception occurred while iterating over the results of a query for context type 'Bit.Infrastructure.EntityFramework.Repositories.DatabaseContext'.
System.Text.Json.JsonException: The JSON value could not be converted to System.Collections.Generic.Dictionary`2[System.Guid,System.Guid]. Path: $ | LineNumber: 0 | BytePositionInLine: 4.
 ---> System.FormatException: The JSON value is not in a supported Guid format.
   at System.Text.Json.Serialization.Converters.GuidConverter.ReadAsPropertyNameCore(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options)
   at System.Text.Json.Serialization.JsonDictionaryConverter`3.<OnTryRead>g__ReadDictionaryKey|10_0(Utf8JsonReader& reader, ReadStack& state, <>c__DisplayClass10_0& )
   at System.Text.Json.Serialization.JsonDictionaryConverter`3.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, TDictionary& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, Utf8JsonReader& reader, Exception ex)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo jsonTypeInfo, Nullable`1 actualByteCount)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 json, JsonTypeInfo jsonTypeInfo)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options)
   at Bit.Infrastructure.EntityFramework.Repositories.Queries.UserCipherDetailsQuery.GetFolderId(Nullable`1 userId, Cipher cipher) in /source/src/Infrastructure.EntityFramework/Repositories/Queries/UserCipherDetailsQuery.cs:line 89
   at lambda_method487(Closure , QueryContext , DbDataReader , ResultContext , SingleQueryResultCoordinator )
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()

### Githash Version

3997defe-dirty

### Environment Details

- OS: Raspbian GNU/Linux 11 (bullseye)
- Environment: Docker
- Docker version 20.10.5+dfsg1
- Docker-compose: docker-compose version 1.25.0,
- Hardware: rpi 4 8GB

### Database Image

postgres:14

### Issue-Link

https://github.com/bitwarden/server/issues/2480

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by justindbaur** [comment] 2023-01-13 21:30
I believe this is a duplicate of #2561 so please subscribe to that one so you can be notified once it's fixed.

**Closed by justindbaur** 2023-01-13 21:30 UTC
Labels: bug, bw-unified-deploy
