### ISSUE TITLE
identity container in a restart loop

### ISSUE THREAD

**Issue by BigZas** [bitwarden/server#557] opened 2019-08-28 16:41 UTC
Hi,

_This issue is similar to the #157 but I can't resolve it yet._

I'm working on :
- Synology RS815+ with 16 Go RAM memory.
- DSM 6.2.2-24922 Update 3
- Docker

The issue is about the identity container that is restarting every minutes approximatively. 

When I go to Docker/Container/bitwarden-identity/Journal I got this : 
```
Unhandled Exception: System.ArgumentNullException: Value cannot be null.

Parameter name: certificate
   at Microsoft.Extensions.DependencyInjection.IdentityServerBuilderExtensionsCrypto.AddSigningCredential(IIdentityServerBuilder builder, X509Certificate2 certificate)
   at Bit.Core.Utilities.ServiceCollectionExtensions.AddCustomIdentityServerServices(IServiceCollection services, IHostingEnvironment env, GlobalSettings globalSettings) in /home/appveyor/projects/server/src/Core/Utilities/ServiceCollectionExtensions.cs:line 340
   at Bit.Identity.Startup.ConfigureServices(IServiceCollection services) in /home/appveyor/projects/server/src/Identity/Startup.cs:line 61
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.Initialize()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at Bit.Identity.Program.Main(String[] args) in /home/appveyor/projects/server/src/Identity/Program.cs:line 13
```
I'm using Let's Encrypt certificate created from the Synology and use by the reverse proxy : 

![image](https://user-images.githubusercontent.com/54637473/63875138-18990d00-c9c3-11e9-97bf-d1ecdd3bb23f.png)
![image](https://user-images.githubusercontent.com/54637473/63875150-1df65780-c9c3-11e9-88d8-8b8000658330.png)

Could you help me please to find out where the issue is?

Thanks for your help ! :)
Regards

**Comment by Gitsko** [comment] 2019-08-29 11:09
Whitch Docker Package version do you use?

I have the same problem after the downgrade to Docker package 17.05.0-0401. I go via SSH on the shell an run `bitwarden.sh selfupdate`  and `bitwarden.sh update`, after this commands bitwarden runs.

**Comment by Snowrisk** [comment] 2019-08-29 11:29
Exactly the same here. but using my own ssl-certificate without reverse proxy
Synolgy DSM 6.2.2-24922 Update 3 (since yesterday)
Docker 18.09.0-0505

**Comment by BigZas** [comment] 2019-08-29 12:47
I did resolved the issue with the solution given on the issue #555 .
 
> Exactly the same here. but using my own ssl-certificate without reverse proxy
> Synolgy DSM 6.2.2-24922 Update 3 (since yesterday)
> Docker 18.09.0-0505
> 
> bitwarden.sh updateself or bitwarden.sh update
> do not solve the problem

You need to roll back to the Docker version. To do this, you need to follow this instructions : 

1) Go by ssh terminal (using putty on Windows) to stop bitwarden 
> ;/bitwarden.sh stop 
2) Delete the Docker application WITHOUT deleting the files.
3) You go to [https://archive.synology.com/download/Package/spk/Docker/17.05.0-0401/]
4) You download the SPK file. 
5) You install it manually on the Synology
6) You start Docker
7) Go back to the terminal and do :
> ./bitwarden.sh rebuild
> ./bitwarden.sh start

**Comment by Snowrisk** [comment] 2019-08-29 12:58
Thanks. it worked perfectly.

**Comment by Snowrisk** [comment] 2019-08-29 13:01
Closes #557

**Comment by evakq8r** [comment] 2019-09-01 03:40
+1 to the above fix; that worked beautifully. Thanks OP!

Seems the latest Synology Docker image has its own problems (not just bitwarden related), as when it installed for me, the docker didn't want to restart without forcing a hard-start using the synoservice command. :\

**Comment by ThoSt81** [comment] 2019-09-08 20:06
+1, had the same issue! Would be great to communicte such known issues somehow :)

**Comment by L4rS6** [comment] 2019-09-13 12:39
> 1. Delete the Docker application WITHOUT deleting the files.
> 2. You go to [https://archive.synology.com/download/Package/spk/Docker/17.05.0-0401/]
> 3. You download the SPK file.
> 4. You install it manually on the Synology
> 5. You start Docker
> 6. Go back to the terminal and do :

How can I revert to the "official" pkg from the synology archive repo as soon as this bug has been fixed?

**Comment by evakq8r** [comment] 2019-09-13 12:47
That (to my understanding anyway) IS the official pkg. It also looks like they've pulled 18.09.0-0506 docker update from the Package Centre, as my DSM only indicates 17.05.0-0401 as the latest version available (is still available in the archive repo though).

**Comment by marcelloceschia** [comment] 2019-09-13 13:34
see: https://community.synology.com/enu/forum/1/post/128313

**Comment by djsmith85** [comment] 2021-11-09 14:18
Closing this issue as it appears the originally posted problem has been resolved. If this happens again or continues to be an issue please feel free to re-open this issue and let us know, along with any additional detail to assist with reproduction and root cause analysis.

**Closed by djsmith85** 2021-11-09 14:18 UTC
