### ISSUE TITLE
PPA all the things?

### ISSUE THREAD

**Issue by BloodyIron** [bitwarden/server#525] opened 2019-07-04 01:39 UTC
Can we please get a PPA/repo setup for Deb/other packages for all aspects of bitwarden? Server/Desktop/Web, etc.

Much appreciated packages are provided, but a PPA/repo would really seal the deal for future updates! :D

**Comment by kspearrin** [comment] 2019-07-04 01:51
Sorry, but I do not know anything about PPA/repo. We provide a .deb package for the desktop app already.

**Comment by BloodyIron** [comment] 2019-07-04 14:05
Repositories help keep things up to date a lot! It's also not really all that hard to setup and can be automated for distribution of updates. Can you please consider it and look into it? That would be awesome! :D 

It's commonplace for how so many other things get updated, like Apache, MySQL and others.

**Comment by kspearrin** [comment] 2019-07-04 14:18
Seems to be a duplicate of https://community.bitwarden.com/t/provide-software-repositories-for-linux-packages/101

**Closed by kspearrin** 2019-07-04 14:18 UTC

**Comment by BloodyIron** [comment] 2019-07-04 21:34
Okay well I don't see why we should close this since this is an actual feature request and is recent.

**Comment by BloodyIron** [comment] 2020-04-06 21:25
Can we re-open this please?

**Comment by tgreer-bw** [comment] 2020-04-06 21:30
We keep the issues to just items that are ‘broken’ - we’ve moved all feature requests to the community forums. Please feel free to post and vote for this item here: [https://community.bitwarden.com/t/provide-software-repositories-for-linux-packages/101](https://community.bitwarden.com/t/provide-software-repositories-for-linux-packages/101)

**Comment by BloodyIron** [comment] 2020-04-06 22:22
LOL I have to say having two trackers like that is just doubling effort and work. So many open source (majority) projects use the GitHub issues for bugs and feature requests. But whatever, I don't think I'm being taken seriously here anyways.
