### ISSUE TITLE
Upgrade from 1.30.0 to 1.31.0 Issues

### ISSUE THREAD

**Issue by tstraus13** [bitwarden/server#542] opened 2019-07-30 19:25 UTC
Hello,

I recently attempted to upgrade my bitwarden docker installation to the latest and afterwords I could no longer access bitwarden. I noticed it was something with the mssql instance because all the errors in the logs showed that other pieces of bitwarden were unable to connect to the database. I then had to spend hours rolling back to 1.27.0 and restoring one of the nightly backups that bitwarden makes. I then slowly incrementally updated to 1.28.0, 1.29.0, and 1.30.0 without issues. Then when I tried going from 1.30.0 to 1.31.0 it broke the installation. The mssql instance does not start correctly and the database migration process never occurs with error related to being unable to connect to the mssql instance. I then rolled back to 1.30.0 and it is now currently working. Has anyone run into a similar issue or know what the issue may be? I would like to be running the latest version for security patches and other bug fixes. Thanks.

**Comment by kspearrin** [comment] 2019-07-30 19:46
Do you see anything in the logs that show what the issue is? You can look in ./bwdata/logs/mssql

Another thing that would help would be starting the installation manually and looking at the container output. The mssql container should have useful information in sdout.

```
cd ./bwdata/docker
docker-compose up
```

**Comment by tstraus13** [comment] 2019-07-30 21:41
Hello,

I will post the logs from the mssql and identity instance.

[errorlog.txt](https://github.com/bitwarden/server/files/3448955/mssql_errorlog.txt)

[20190730.txt](https://github.com/bitwarden/server/files/3448951/identity_20190730.txt)

It seems like the identity cannot connect but I'm not sure why the mssql instance isn't working.

Thanks

**Comment by kspearrin** [comment] 2019-07-30 23:56
Is the mssql container running without issue? What is the status of `docker ps`?

**Comment by tstraus13** [comment] 2019-07-31 00:59
No here is the issues I am seeing during migration and here is docker ps. It seems there is a database issue. If I rollback to 1.30.0 it works fine. Thanks.

[migration_error.txt](https://github.com/bitwarden/server/files/3449347/migration_error.txt)
[docker_ps.txt](https://github.com/bitwarden/server/files/3449348/docker_ps.txt)

**Comment by kspearrin** [comment] 2019-07-31 13:23
Weird. What if you only roll back the mssql container to 1.30.0 as a test? You should be able to do this by modifying the ./bwdata/docker/docker-compose.yml file.

**Comment by tstraus13** [comment] 2019-07-31 21:10
When I try that then the nginx container breaks. I did not see any issues in the logs either. So I tried running the mssql and nginx at 1.30.0 and the rest at 1.31.0 and it seems to be working now.

**Comment by tstraus13** [comment] 2019-10-23 02:14
This is still an issue. I just today tried to go from 1.30.0 to 1.32.0 and the MSSQL instance fails to start and results in the database failing to update/upgrade.

**Comment by djsmith85** [comment] 2021-12-16 11:52
Hi @tstraus13, it appears we've not heard from you about this issue in some time. While we are now closing this issue, if it continues to be a problem please feel free to re-open this issue and provide any further information that may be helpful in reproducing the problem or helping you further.

**Closed by djsmith85** 2021-12-16 11:52 UTC
